:-module(electromagnetism,[]).
units:alias(isq:volume_electric_charge,isq:electric_charge_density).
units:alias(isq:volumic_charge,isq:electric_charge_density).
units:alias(isq:areic_electric_charge,isq:surface_density_of_electric_charge).
units:alias(isq:areic_charge,isq:surface_density_of_electric_charge).
units:alias(isq:lineic_electric_charge,isq:linear_density_of_electric_charge).
units:alias(isq:lineic_charge,isq:linear_density_of_electric_charge).
units:alias(isq:electric_tension,isq:voltage).
units:alias(isq:electric_displacement,isq:electric_flux_density).
units:alias(isq:permeability_of_vacuum,isq:magnetic_constant).
units:alias(isq:light_speed_in_vacuum,isq:speed_of_light_in_vacuum).
units:alias(isq:luminal_speed,isq:speed_of_light_in_vacuum).
units:alias(isq:permittivity_of_vacuum,isq:electric_constant).
units:alias(isq:magnetic_area_moment,isq:magnetic_moment).
units:alias(isq:magnetizing_field,isq:magnetic_field_strength).
units:alias(isq:coercive_field_strength,isq:coercivity).
units:alias(isq:source_tension,isq:source_voltage).
units:alias(isq:self_inductance,isq:inductance).
units:alias(isq:instantaneous_power,isq:electromagnetism_power).
units:alias(isq:electric_tension_phasor,isq:voltage_phasor).
units:alias(isq:complex_impedance,isq:impedance).
units:alias(isq:wave_impedance_in_vacuum,isq:impedance_of_vacuum).
units:alias(isq:complex_admittance,isq:admittance).
units:quantity_character(isq:electric_potential,quantity_character:real_scalar).
units:quantity_character(isq:electric_potential_difference,quantity_character:real_scalar).
units:quantity_character(isq:magnetic_flux_density,quantity_character:vector).
units:quantity_character(isq:permittivity,quantity_character:real_scalar).
units:quantity_character(isq:electric_susceptibility,quantity_character:real_scalar).
units:quantity_character(isq:electric_flux,quantity_character:real_scalar).
units:quantity_character(isq:displacement_current,quantity_character:real_scalar).
units:quantity_character(isq:magnetic_flux,quantity_character:real_scalar).
units:quantity_character(isq:protoflux,quantity_character:real_scalar).
units:quantity_character(isq:magnetic_moment,quantity_character:vector).
units:quantity_character(isq:permeability,quantity_character:real_scalar).
units:quantity_character(isq:magnetic_susceptibility,quantity_character:real_scalar).
units:quantity_character(isq:coercivity,quantity_character:real_scalar).
units:quantity_character(isq:electromagnetic_energy_density,quantity_character:real_scalar).
units:quantity_character(isq:magnetic_tension,quantity_character:real_scalar).
units:quantity_character(isq:magnetomotive_force,quantity_character:real_scalar).
units:quantity_character(isq:conductivity,quantity_character:real_scalar).
units:quantity_character(isq:electric_current_phasor,quantity_character:complex_scalar).
units:quantity_character(isq:voltage_phasor,quantity_character:complex_scalar).
units:quantity_character(isq:resistance_to_alternating_current,quantity_character:real_scalar).
units:quantity_character(isq:reactance,quantity_character:real_scalar).
units:quantity_character(isq:apparent_impedance,quantity_character:real_scalar).
units:quantity_character(isq:conductance_for_alternating_current,quantity_character:real_scalar).
units:quantity_character(isq:susceptance,quantity_character:real_scalar).
units:quantity_character(isq:apparent_admittance,quantity_character:real_scalar).
units:quantity_character(isq:apparent_power,quantity_character:real_scalar).
units:quantity_formula(isq:relative_permittivity,(isq:permittivity)/(isq:electric_constant)).
units:quantity_formula(isq:electric_susceptibility,(isq:electric_polarization)/(isq:electric_constant)/(isq:electric_field_strength)).
units:quantity_formula(isq:displacement_current,(isq:displacement_current_density)*(isq:area)).
units:quantity_formula(isq:relative_permeability,(isq:permeability)/(isq:magnetic_constant)).
units:quantity_formula(isq:magnetic_susceptibility,(isq:magnetization)/(isq:magnetic_field_strength)).
units:quantity_formula(isq:magnetic_tension,(isq:magnetic_field_strength)*(isq:position_vector)).
units:quantity_formula(isq:magnetomotive_force,(isq:magnetic_field_strength)*(isq:position_vector)).
units:quantity_formula(isq:coupling_factor,(isq:mutual_inductance)/((isq:self_inductance)**2)**(1/2)).
units:quantity_formula(isq:leakage_factor,(isq:coupling_factor)**2).
units:quantity_formula(isq:electromagnetism_power,(isq:voltage)*(isq:electric_current)).
units:quantity_formula(isq:admittance_of_vacuum,1/(isq:impedance_of_vacuum)).
units:quantity_formula(isq:quality_factor,(isq:reactance)/(isq:resistance)).
units:quantity_formula(isq:loss_factor,1/(isq:quality_factor)).
units:quantity_formula(isq:active_power,1/(isq:period)*((isq:instantaneous_power)*(isq:time))).
units:quantity_formula(isq:power_factor,(isq:active_power)/(isq:apparent_power)).
units:quantity_parent(isq:electric_charge,(isq:electric_current)*(isq:time)).
units:quantity_parent(isq:elementary_charge,isq:electric_charge).
units:quantity_parent(isq:electric_charge_density,(isq:electric_charge)/(isq:volume)).
units:quantity_parent(isq:surface_density_of_electric_charge,(isq:electric_charge)/(isq:area)).
units:quantity_parent(isq:linear_density_of_electric_charge,(isq:electric_charge)/(isq:length)).
units:quantity_parent(isq:electric_dipole_moment,(isq:electric_charge)*(isq:displacement)).
units:quantity_parent(isq:electric_polarization,(isq:electric_dipole_moment)/(isq:volume)).
units:quantity_parent(isq:electric_current_density,(isq:electric_charge_density)*(isq:velocity)).
units:quantity_parent(isq:linear_electric_current_density,(isq:surface_density_of_electric_charge)*(isq:velocity)).
units:quantity_parent(isq:electric_field_strength,(isq:force)/(isq:electric_charge)).
units:quantity_parent(isq:electric_potential,(isq:electric_field_strength)*(isq:length)).
units:quantity_parent(isq:electric_potential_difference,isq:electric_potential).
units:quantity_parent(isq:voltage,isq:electric_potential).
units:quantity_parent(isq:induced_voltage,isq:voltage).
units:quantity_parent(isq:electric_flux_density,isq:electric_polarization).
units:quantity_parent(isq:capacitance,(isq:electric_charge)/(isq:voltage)).
units:quantity_parent(isq:magnetic_flux_density,(isq:force)/((isq:electric_charge)*(isq:velocity))).
units:quantity_parent(isq:magnetic_constant,(isq:electric_potential)*(isq:time)/((isq:electric_current)*(isq:length))).
units:quantity_parent(isq:phase_speed_of_electromagnetic_waves,(isq:angular_frequency)/(isq:angular_wavenumber)).
units:quantity_parent(isq:speed_of_light_in_vacuum,isq:speed).
units:quantity_parent(isq:electric_constant,1/((isq:magnetic_constant)*(isq:speed_of_light_in_vacuum)**2)).
units:quantity_parent(isq:permittivity,(isq:electric_flux_density)/(isq:electric_field_strength)).
units:quantity_parent(isq:relative_permittivity,1).
units:quantity_parent(isq:electric_susceptibility,1).
units:quantity_parent(isq:electric_flux,(isq:electric_flux_density)*(isq:area)).
units:quantity_parent(isq:displacement_current_density,(isq:electric_flux_density)/(isq:time)).
units:quantity_parent(isq:displacement_current,isq:electric_current).
units:quantity_parent(isq:total_current,isq:electric_current).
units:quantity_parent(isq:total_current_density,isq:electric_current_density).
units:quantity_parent(isq:magnetic_flux,(isq:magnetic_flux_density)*(isq:area)).
units:quantity_parent(isq:magnetic_vector_potential,(isq:magnetic_flux_density)*(isq:length)).
units:quantity_parent(isq:protoflux,(isq:magnetic_vector_potential)*(isq:displacement)).
units:quantity_parent(isq:linked_magnetic_flux,isq:magnetic_flux).
units:quantity_parent(isq:total_magnetic_flux,isq:magnetic_flux).
units:quantity_parent(isq:magnetic_moment,(isq:electric_current)*(isq:area)).
units:quantity_parent(isq:magnetization,(isq:magnetic_moment)/(isq:volume)).
units:quantity_parent(isq:magnetic_field_strength,isq:magnetization).
units:quantity_parent(isq:permeability,(isq:magnetic_flux_density)/(isq:magnetic_field_strength)).
units:quantity_parent(isq:relative_permeability,1).
units:quantity_parent(isq:magnetic_susceptibility,1).
units:quantity_parent(isq:magnetic_polarization,(isq:magnetic_constant)*(isq:magnetization)).
units:quantity_parent(isq:magnetic_dipole_moment,(isq:magnetic_constant)*(isq:magnetic_moment)).
units:quantity_parent(isq:coercivity,isq:magnetic_field_strength).
units:quantity_parent(isq:electromagnetic_energy_density,(isq:electric_field_strength)*(isq:electric_flux_density)).
units:quantity_parent(isq:'Poynting_vector',(isq:electric_field_strength)*(isq:magnetic_field_strength)).
units:quantity_parent(isq:source_voltage,isq:voltage).
units:quantity_parent(isq:magnetic_potential,isq:electric_current).
units:quantity_parent(isq:magnetic_tension,isq:electric_current).
units:quantity_parent(isq:magnetomotive_force,isq:electric_current).
units:quantity_parent(isq:number_of_turns_in_a_winding,1).
units:quantity_parent(isq:reluctance,(isq:magnetic_tension)/(isq:magnetic_flux)).
units:quantity_parent(isq:permeance,1/(isq:reluctance)).
units:quantity_parent(isq:inductance,(isq:protoflux)/(isq:electric_current)).
units:quantity_parent(isq:mutual_inductance,(isq:protoflux)/(isq:electric_current)).
units:quantity_parent(isq:coupling_factor,1).
units:quantity_parent(isq:leakage_factor,1).
units:quantity_parent(isq:conductivity,(isq:electric_current_density)/(isq:electric_field_strength)).
units:quantity_parent(isq:resistivity,1/(isq:conductivity)).
units:quantity_parent(isq:electromagnetism_power,isq:power).
units:quantity_parent(isq:resistance,(isq:voltage)/(isq:electric_current)).
units:quantity_parent(isq:conductance,1/(isq:resistance)).
units:quantity_parent(isq:phase_difference,isq:phase_angle).
units:quantity_parent(isq:electric_current_phasor,isq:electric_current).
units:quantity_parent(isq:voltage_phasor,isq:voltage).
units:quantity_parent(isq:impedance,(isq:voltage_phasor)/(isq:electric_current_phasor)).
units:quantity_parent(isq:impedance_of_vacuum,isq:impedance).
units:quantity_parent(isq:resistance_to_alternating_current,isq:impedance).
units:quantity_parent(isq:reactance,isq:impedance).
units:quantity_parent(isq:apparent_impedance,isq:impedance).
units:quantity_parent(isq:admittance,1/(isq:impedance)).
units:quantity_parent(isq:admittance_of_vacuum,isq:admittance).
units:quantity_parent(isq:conductance_for_alternating_current,isq:conductance).
units:quantity_parent(isq:susceptance,isq:admittance).
units:quantity_parent(isq:apparent_admittance,isq:admittance).
units:quantity_parent(isq:quality_factor,1).
units:quantity_parent(isq:loss_factor,1).
units:quantity_parent(isq:loss_angle,isq:angular_measure).
units:quantity_parent(isq:active_power,isq:power).
units:quantity_parent(isq:complex_power,(isq:voltage_phasor)*(isq:electric_current_phasor)).
units:quantity_parent(isq:apparent_power,isq:complex_power).
units:quantity_parent(isq:power_factor,1).
units:quantity_parent(isq:reactive_power,(isq:mass)*(isq:length)**2/(isq:time)**3).
units:quantity_parent(isq:non_active_power,((isq:apparent_power)**2)**(1/2)).
units:quantity_parent(isq:active_energy,(isq:instantaneous_power)*(isq:time)).
