:-module(information_science_and_technology,[]).
units:alias(isq:traffic_load,isq:traffic_carried_intensity).
units:alias(isq:calling_rate,isq:call_intensity).
units:alias(isq:storage_size,isq:storage_capacity).
units:alias(isq:bit_rate,isq:binary_digit_rate).
units:alias(isq:bit_period,isq:period_of_binary_digits).
units:alias(isq:equivalent_bit_rate,isq:bit_rate).
units:alias(isq:line_digit_rate,isq:modulation_rate).
units:alias(isq:clock_rate,isq:clock_frequency).
units:dimension_symbol(isq:dim_traffic_intensity,'A').
units:kind(isq:storage_capacity).
units:quantity_formula(isq:period_of_data_elements,1/(isq:transfer_rate)).
units:quantity_formula(isq:period_of_binary_digits,1/(isq:binary_digit_rate)).
units:quantity_parent(isq:traffic_intensity,isq:dim_traffic_intensity).
units:quantity_parent(isq:traffic_offered_intensity,isq:traffic_intensity).
units:quantity_parent(isq:traffic_carried_intensity,isq:traffic_intensity).
units:quantity_parent(isq:mean_queue_length,1).
units:quantity_parent(isq:loss_probability,1).
units:quantity_parent(isq:waiting_probability,1).
units:quantity_parent(isq:call_intensity,1/(isq:duration)).
units:quantity_parent(isq:completed_call_intensity,isq:call_intensity).
units:quantity_parent(isq:storage_capacity,1).
units:quantity_parent(isq:equivalent_binary_storage_capacity,isq:storage_capacity).
units:quantity_parent(isq:transfer_rate,(isq:storage_capacity)/(isq:duration)).
units:quantity_parent(isq:period_of_data_elements,isq:period).
units:quantity_parent(isq:binary_digit_rate,isq:transfer_rate).
units:quantity_parent(isq:period_of_binary_digits,isq:period).
units:quantity_parent(isq:equivalent_binary_digit_rate,isq:binary_digit_rate).
units:quantity_parent(isq:modulation_rate,1/(isq:duration)).
units:quantity_parent(isq:quantizing_distortion_power,isq:power).
units:quantity_parent(isq:carrier_power,isq:power).
units:quantity_parent(isq:signal_energy_per_binary_digit,(isq:carrier_power)*(isq:period_of_binary_digits)).
units:quantity_parent(isq:error_probability,1).
units:quantity_parent(isq:'Hamming_distance',1).
units:quantity_parent(isq:clock_frequency,isq:frequency).
units:quantity_parent(isq:decision_content,1).
