:-module(light_and_radiation,[]).
units:alias(isq:radiant_power,isq:radiant_flux).
units:alias(isq:spectral_radiant_power,isq:spectral_radiant_flux).
units:quantity_formula(isq:refractive_index,(isq:speed_of_light_in_vacuum)/(isq:speed_of_light_in_a_medium)).
units:quantity_formula(isq:radiant_flux,(isq:radiant_energy)/(isq:time)).
units:quantity_parent(isq:speed_of_light_in_a_medium,isq:speed).
units:quantity_parent(isq:refractive_index,1).
units:quantity_parent(isq:radiant_energy,isq:energy).
units:quantity_parent(isq:spectral_radiant_energy,(isq:radiant_energy)/(isq:wavelength)).
units:quantity_parent(isq:radiant_energy_density,(isq:radiant_energy)/(isq:volume)).
units:quantity_parent(isq:spectral_radiant_energy_density_in_terms_of_wavelength,(isq:radiant_energy_density)/(isq:wavelength)).
units:quantity_parent(isq:spectral_radiant_energy_density_in_terms_of_wavenumber,(isq:radiant_energy_density)/(isq:wavenumber)).
units:quantity_parent(isq:radiant_flux,isq:power).
units:quantity_parent(isq:spectral_radiant_flux,(isq:radiant_flux)/(isq:wavelength)).
units:quantity_parent(isq:radiant_intensity,(isq:radiant_flux)/(isq:solid_angular_measure)).
units:quantity_parent(isq:spectral_radiant_intensity,(isq:radiant_intensity)/(isq:wavelength)).
units:quantity_parent(isq:radiance,(isq:radiant_intensity)/(isq:area)).
units:quantity_parent(isq:spectral_radiance,(isq:radiance)/(isq:wavelength)).
units:quantity_parent(isq:irradiance,(isq:radiant_flux)/(isq:area)).
units:quantity_parent(isq:spectral_irradiance,(isq:irradiance)/(isq:wavelength)).
units:quantity_parent(isq:radiant_exitance,(isq:radiant_flux)/(isq:area)).
units:quantity_parent(isq:spectral_radiant_exitance,(isq:radiant_exitance)/(isq:wavelength)).
units:quantity_parent(isq:radiant_exposure,(isq:radiant_energy)/(isq:area)).
units:quantity_parent(isq:spectral_radiant_exposure,(isq:radiant_exposure)/(isq:wavelength)).
