:-module(si_quantities,[]).
units:alias(isq:breadth,isq:width).
units:alias(isq:arc_length,isq:path_length).
units:alias(isq:period,isq:period_duration).
units:kind(isq:angular_measure).
units:kind(isq:solid_angular_measure).
units:quantity_formula(isq:angular_measure,(isq:arc_length)/(isq:radius)).
units:quantity_formula(isq:solid_angular_measure,(isq:area)/(isq:radius)**2).
units:quantity_parent(isq:width,isq:length).
units:quantity_parent(isq:radius,isq:width).
units:quantity_parent(isq:path_length,isq:length).
units:quantity_parent(isq:area,(isq:length)**2).
units:quantity_parent(isq:angular_measure,1).
units:quantity_parent(isq:solid_angular_measure,1).
units:quantity_parent(isq:period_duration,isq:duration).
units:quantity_parent(isq:frequency,1/(isq:period_duration)).
units:quantity_parent(isq:energy,(isq:mass)*(isq:length)**2/(isq:time)**2).
units:quantity_parent(isq:activity,1/(isq:duration)).
units:quantity_parent(isq:absorbed_dose,(isq:energy)/(isq:mass)).
units:quantity_parent(isq:ionizing_radiation_quality_factor,1).
units:quantity_parent(isq:dose_equivalent,(isq:absorbed_dose)*(isq:ionizing_radiation_quality_factor)).
