:-module(space_and_time,[]).
units:alias(isq:depth,isq:height).
units:alias(isq:altitude,isq:height).
units:alias(isq:angular_displacement,isq:rotational_displacement).
units:alias(isq:wavenumber,isq:repetency).
units:alias(isq:angular_wavenumber,isq:angular_repetency).
units:alias(isq:extinction,isq:attenuation).
units:quantity_character(isq:displacement,quantity_character:vector).
units:quantity_character(isq:angular_velocity,quantity_character:vector).
units:quantity_character(isq:wave_vector,quantity_character:vector).
units:quantity_formula(isq:rotational_displacement,(isq:path_length)/(isq:radius)).
units:quantity_formula(isq:velocity,(isq:displacement)/(isq:duration)).
units:quantity_formula(isq:logarithmic_decrement,(isq:damping_coefficient)*(isq:period_duration)).
units:quantity_parent(isq:height,isq:length).
units:quantity_parent(isq:thickness,isq:width).
units:quantity_parent(isq:diameter,isq:width).
units:quantity_parent(isq:distance,isq:path_length).
units:quantity_parent(isq:radial_distance,isq:distance).
units:quantity_parent(isq:displacement,isq:length).
units:quantity_parent(isq:position_vector,isq:displacement).
units:quantity_parent(isq:radius_of_curvature,isq:radius).
units:quantity_parent(isq:curvature,1/(isq:radius_of_curvature)).
units:quantity_parent(isq:volume,(isq:length)**3).
units:quantity_parent(isq:rotational_displacement,isq:angular_measure).
units:quantity_parent(isq:phase_angle,isq:angular_measure).
units:quantity_parent(isq:speed,(isq:length)/(isq:time)).
units:quantity_parent(isq:velocity,isq:speed).
units:quantity_parent(isq:acceleration,(isq:velocity)/(isq:duration)).
units:quantity_parent(isq:acceleration_of_free_fall,isq:acceleration).
units:quantity_parent(isq:angular_velocity,(isq:angular_displacement)/(isq:duration)).
units:quantity_parent(isq:angular_acceleration,(isq:angular_velocity)/(isq:duration)).
units:quantity_parent(isq:time_constant,isq:duration).
units:quantity_parent(isq:rotation,1).
units:quantity_parent(isq:rotational_frequency,(isq:rotation)/(isq:duration)).
units:quantity_parent(isq:angular_frequency,(isq:phase_angle)/(isq:duration)).
units:quantity_parent(isq:wavelength,isq:length).
units:quantity_parent(isq:repetency,1/(isq:wavelength)).
units:quantity_parent(isq:wave_vector,isq:repetency).
units:quantity_parent(isq:angular_repetency,1/(isq:wavelength)).
units:quantity_parent(isq:phase_speed,(isq:angular_frequency)/(isq:angular_repetency)).
units:quantity_parent(isq:group_speed,(isq:angular_frequency)/(isq:angular_repetency)).
units:quantity_parent(isq:damping_coefficient,1/(isq:time_constant)).
units:quantity_parent(isq:logarithmic_decrement,1).
units:quantity_parent(isq:attenuation,1/(isq:distance)).
units:quantity_parent(isq:phase_coefficient,(isq:phase_angle)/(isq:path_length)).
units:quantity_parent(isq:propagation_coefficient,1/(isq:length)).
