:-module(thermodynamics,[]).
units:alias(isq:amount_of_heat,isq:heat).
units:alias(isq:coefficient_of_thermal_insulance,isq:thermal_insulance).
units:alias(isq:isentropic_expansion_factor,isq:isentropic_exponent).
units:alias(isq:thermodynamic_energy,isq:internal_energy).
units:alias(isq:'Helmholtz_function',isq:'Helmholtz_energy').
units:alias(isq:'Gibbs_function',isq:'Gibbs_energy').
units:alias(isq:specific_thermodynamic_energy,isq:specific_internal_energy).
units:alias(isq:specific_Helmholtz_function,isq:specific_Helmholtz_energy).
units:alias(isq:specific_Gibbs_function,isq:specific_Gibbs_energy).
units:quantity_formula(isq:ratio_of_specific_heat_capacities,(isq:specific_heat_capacity_at_constant_pressure)/(isq:specific_heat_capacity_at_constant_volume)).
units:quantity_formula(isq:thermodynamic_efficiency,(isq:work)/(isq:heat)).
units:quantity_parent(isq:'Celsius_temperature',isq:thermodynamic_temperature).
units:quantity_parent(isq:linear_expansion_coefficient,1/(isq:length)*((isq:length)/(isq:thermodynamic_temperature))).
units:quantity_parent(isq:cubic_expansion_coefficient,1/(isq:volume)*((isq:volume)/(isq:thermodynamic_temperature))).
units:quantity_parent(isq:relative_pressure_coefficient,1/(isq:pressure)*((isq:pressure)/(isq:thermodynamic_temperature))).
units:quantity_parent(isq:pressure_coefficient,(isq:pressure)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:isothermal_compressibility,1/(isq:volume)*((isq:volume)/(isq:pressure))).
units:quantity_parent(isq:isentropic_compressibility,1/(isq:volume)*((isq:volume)/(isq:pressure))).
units:quantity_parent(isq:heat,isq:energy).
units:quantity_parent(isq:latent_heat,isq:heat).
units:quantity_parent(isq:heat_flow_rate,(isq:heat)/(isq:time)).
units:quantity_parent(isq:density_of_heat_flow_rate,(isq:heat_flow_rate)/(isq:area)).
units:quantity_parent(isq:thermal_conductivity,(isq:density_of_heat_flow_rate)*((isq:length)/(isq:thermodynamic_temperature))).
units:quantity_parent(isq:coefficient_of_heat_transfer,(isq:density_of_heat_flow_rate)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:surface_coefficient_of_heat_transfer,(isq:density_of_heat_flow_rate)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:thermal_insulance,1/(isq:coefficient_of_heat_transfer)).
units:quantity_parent(isq:thermal_resistance,(isq:thermodynamic_temperature)/(isq:heat_flow_rate)).
units:quantity_parent(isq:thermal_conductance,1/(isq:thermal_resistance)).
units:quantity_parent(isq:heat_capacity,(isq:heat)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:specific_heat_capacity,(isq:heat_capacity)/(isq:mass)).
units:quantity_parent(isq:specific_heat_capacity_at_constant_pressure,isq:specific_heat_capacity).
units:quantity_parent(isq:specific_heat_capacity_at_constant_volume,isq:specific_heat_capacity).
units:quantity_parent(isq:specific_heat_capacity_at_saturated_vapour_pressure,isq:specific_heat_capacity).
units:quantity_parent(isq:thermal_diffusivity,(isq:thermal_conductivity)/((isq:mass_density)*(isq:specific_heat_capacity_at_constant_pressure))).
units:quantity_parent(isq:ratio_of_specific_heat_capacities,1).
units:quantity_parent(isq:isentropic_exponent,(isq:volume)/(isq:pressure)*((isq:pressure)/(isq:volume))).
units:quantity_parent(isq:entropy,(isq:kinetic_energy)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:specific_entropy,(isq:entropy)/(isq:mass)).
units:quantity_parent(isq:enthalpy,isq:energy).
units:quantity_parent(isq:internal_energy,isq:enthalpy).
units:quantity_parent(isq:'Helmholtz_energy',isq:internal_energy).
units:quantity_parent(isq:'Gibbs_energy',isq:enthalpy).
units:quantity_parent(isq:specific_energy,(isq:energy)/(isq:mass)).
units:quantity_parent(isq:specific_internal_energy,(isq:internal_energy)/(isq:mass)).
units:quantity_parent(isq:specific_enthalpy,(isq:enthalpy)/(isq:mass)).
units:quantity_parent(isq:specific_Helmholtz_energy,(isq:'Helmholtz_energy')/(isq:mass)).
units:quantity_parent(isq:specific_Gibbs_energy,(isq:'Gibbs_energy')/(isq:mass)).
units:quantity_parent(isq:'Massieu_function',(isq:'Helmholtz_energy')/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:'Planck_function',(isq:'Gibbs_energy')/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:'Joule_Thomson_coefficient',(isq:thermodynamic_temperature)/(isq:pressure)).
units:quantity_parent(isq:thermodynamic_efficiency,1).
units:quantity_parent(isq:maximum_efficiency,(isq:thermodynamic_temperature)/(isq:thermodynamic_temperature)).
units:quantity_parent(isq:specific_gas_constant,(isq:entropy)/(isq:mass)).
units:quantity_parent(isq:mass_concentration_of_water,(isq:mass)/(isq:volume)).
units:quantity_parent(isq:mass_concentration_of_water_vapour,(isq:mass)/(isq:volume)).
units:quantity_parent(isq:mass_ratio_of_water_to_dry_matter,(isq:mass)/(isq:mass)).
units:quantity_parent(isq:mass_ratio_of_water_vapour_to_dry_gas,(isq:mass)/(isq:mass)).
units:quantity_parent(isq:mass_fraction_of_water,(isq:mass_ratio_of_water_to_dry_matter)/(isq:mass_ratio_of_water_to_dry_matter)).
units:quantity_parent(isq:mass_fraction_of_dry_matter,isq:mass_fraction_of_water).
units:quantity_parent(isq:relative_humidity,(isq:pressure)/(isq:pressure)).
units:quantity_parent(isq:relative_mass_concentration_of_vapour,(isq:mass_concentration_of_water_vapour)/(isq:mass_concentration_of_water_vapour)).
units:quantity_parent(isq:relative_mass_ratio_of_vapour,(isq:mass_ratio_of_water_vapour_to_dry_gas)/(isq:mass_ratio_of_water_vapour_to_dry_gas)).
units:quantity_parent(isq:dew_point_temperature,isq:thermodynamic_temperature).
