:-module(cgs_symbol,['Gal'/1,gal/1,erg/1,'Ba'/1,barye/1,g/1,gram/1,s/1,second/1,'Ky'/1,kayser/1,'P'/1,poise/1,'St'/1,stokes/1,dyn/1,dyne/1]).
'Gal'(:(cgs,gal)).
gal(:(cgs,gal)).
erg(:(cgs,erg)).
'Ba'(:(cgs,barye)).
barye(:(cgs,barye)).
g(:(cgs,gram)).
gram(:(cgs,gram)).
s(:(cgs,second)).
second(:(cgs,second)).
'Ky'(:(cgs,kayser)).
kayser(:(cgs,kayser)).
'P'(:(cgs,poise)).
poise(:(cgs,poise)).
'St'(:(cgs,stokes)).
stokes(:(cgs,stokes)).
dyn(:(cgs,dyne)).
dyne(:(cgs,dyne)).
