:-module(cgs_symbol,[erg/1,dyn/1,dyne/1,'P'/1,poise/1,'St'/1,stokes/1,'Ba'/1,barye/1,s/1,second/1,'K'/1,kayser/1,'Gal'/1,gal/1,g/1,gram/1]).
erg(:(cgs,erg)).
dyn(:(cgs,dyne)).
dyne(:(cgs,dyne)).
'P'(:(cgs,poise)).
poise(:(cgs,poise)).
'St'(:(cgs,stokes)).
stokes(:(cgs,stokes)).
'Ba'(:(cgs,barye)).
barye(:(cgs,barye)).
s(:(cgs,second)).
second(:(cgs,second)).
'K'(:(cgs,kayser)).
kayser(:(cgs,kayser)).
'Gal'(:(cgs,gal)).
gal(:(cgs,gal)).
g(:(cgs,gram)).
gram(:(cgs,gram)).
