:-module(cgs_symbol,['Gal'/1,gal/1,erg/1,'Ba'/1,barye/1,dyn/1,dyne/1,s/1,second/1,'St'/1,stokes/1,g/1,gram/1,'P'/1,poise/1,'K'/1,kayser/1]).
'Gal'(:(cgs,gal)).
gal(:(cgs,gal)).
erg(:(cgs,erg)).
'Ba'(:(cgs,barye)).
barye(:(cgs,barye)).
dyn(:(cgs,dyne)).
dyne(:(cgs,dyne)).
s(:(cgs,second)).
second(:(cgs,second)).
'St'(:(cgs,stokes)).
stokes(:(cgs,stokes)).
g(:(cgs,gram)).
gram(:(cgs,gram)).
'P'(:(cgs,poise)).
poise(:(cgs,poise)).
'K'(:(cgs,kayser)).
kayser(:(cgs,kayser)).
