:-module(si_symbol,[qK/1,rK/1,yK/1,zK/1,aK/1,fK/1,pK/1,nK/1,µK/1,mK/1,cK/1,dK/1,daK/1,hK/1,kK/1,'MK'/1,'GK'/1,'TK'/1,'PK'/1,'EK'/1,'ZK'/1,'YK'/1,'RK'/1,'QK'/1,'K'/1,kelvin/1,qJ/1,rJ/1,yJ/1,zJ/1,aJ/1,fJ/1,pJ/1,nJ/1,µJ/1,mJ/1,cJ/1,dJ/1,daJ/1,hJ/1,kJ/1,'MJ'/1,'GJ'/1,'TJ'/1,'PJ'/1,'EJ'/1,'ZJ'/1,'YJ'/1,'RJ'/1,'QJ'/1,'J'/1,joule/1,qH/1,rH/1,yH/1,zH/1,aH/1,fH/1,pH/1,nH/1,µH/1,mH/1,cH/1,dH/1,daH/1,hH/1,kH/1,'MH'/1,'GH'/1,'TH'/1,'PH'/1,'EH'/1,'ZH'/1,'YH'/1,'RH'/1,'QH'/1,'H'/1,henry/1,qm/1,rm/1,ym/1,zm/1,am/1,fm/1,pm/1,nm/1,µm/1,mm/1,cm/1,dm/1,dam/1,hm/1,km/1,'Mm'/1,'Gm'/1,'Tm'/1,'Pm'/1,'Em'/1,'Zm'/1,'Ym'/1,'Rm'/1,'Qm'/1,m/1,metre/1,qs/1,rs/1,ys/1,zs/1,(as)/1,fs/1,ps/1,ns/1,µs/1,ms/1,cs/1,ds/1,das/1,hs/1,ks/1,'Ms'/1,'Gs'/1,'Ts'/1,'Ps'/1,'Es'/1,'Zs'/1,'Ys'/1,'Rs'/1,'Qs'/1,s/1,second/1,'qg₀'/1,'rg₀'/1,'yg₀'/1,'zg₀'/1,'ag₀'/1,'fg₀'/1,'pg₀'/1,'ng₀'/1,'µg₀'/1,'mg₀'/1,'cg₀'/1,'dg₀'/1,'dag₀'/1,'hg₀'/1,'kg₀'/1,'Mg₀'/1,'Gg₀'/1,'Tg₀'/1,'Pg₀'/1,'Eg₀'/1,'Zg₀'/1,'Yg₀'/1,'Rg₀'/1,'Qg₀'/1,'g₀'/1,standard_gravity/1,qlm/1,rlm/1,ylm/1,zlm/1,alm/1,flm/1,plm/1,nlm/1,µlm/1,mlm/1,clm/1,dlm/1,dalm/1,hlm/1,klm/1,'Mlm'/1,'Glm'/1,'Tlm'/1,'Plm'/1,'Elm'/1,'Zlm'/1,'Ylm'/1,'Rlm'/1,'Qlm'/1,lm/1,lumen/1,qeV/1,reV/1,yeV/1,zeV/1,aeV/1,feV/1,peV/1,neV/1,µeV/1,meV/1,ceV/1,deV/1,daeV/1,heV/1,keV/1,'MeV'/1,'GeV'/1,'TeV'/1,'PeV'/1,'EeV'/1,'ZeV'/1,'YeV'/1,'ReV'/1,'QeV'/1,eV/1,electronvolt/1,qDa/1,rDa/1,yDa/1,zDa/1,aDa/1,fDa/1,pDa/1,nDa/1,µDa/1,mDa/1,cDa/1,dDa/1,daDa/1,hDa/1,kDa/1,'MDa'/1,'GDa'/1,'TDa'/1,'PDa'/1,'EDa'/1,'ZDa'/1,'YDa'/1,'RDa'/1,'QDa'/1,'Da'/1,dalton/1,rt/1,yt/1,zt/1,at/1,nt/1,µt/1,mt/1,ct/1,dt/1,dat/1,ht/1,kt/1,'Mt'/1,'Gt'/1,'Tt'/1,'Pt'/1,'Et'/1,'Zt'/1,'Yt'/1,'Rt'/1,'Qt'/1,t/1,tonne/1,qL/1,rL/1,yL/1,zL/1,aL/1,fL/1,pL/1,nL/1,µL/1,mL/1,cL/1,dL/1,daL/1,hL/1,kL/1,'ML'/1,'GL'/1,'TL'/1,'PL'/1,'EL'/1,'ZL'/1,'YL'/1,'RL'/1,'QL'/1,'L'/1,litre/1,qa/1,ra/1,ya/1,za/1,aa/1,fa/1,pa/1,na/1,µa/1,ma/1,ca/1,da/1,daa/1,ha/1,ka/1,'Ma'/1,'Ga'/1,'Ta'/1,'Ea'/1,'Za'/1,'Ya'/1,'Ra'/1,'Qa'/1,a/1,are/1,'q″'/1,'r″'/1,'y″'/1,'z″'/1,'a″'/1,'f″'/1,'p″'/1,'n″'/1,'µ″'/1,'m″'/1,'c″'/1,'d″'/1,'da″'/1,'h″'/1,'k″'/1,'M″'/1,'G″'/1,'T″'/1,'P″'/1,'E″'/1,'Z″'/1,'Y″'/1,'R″'/1,'Q″'/1,″ / 1,arcsecond/1,qA/1,rA/1,yA/1,zA/1,aA/1,fA/1,pA/1,nA/1,µA/1,mA/1,cA/1,dA/1,daA/1,hA/1,kA/1,'MA'/1,'GA'/1,'TA'/1,'PA'/1,'EA'/1,'ZA'/1,'YA'/1,'RA'/1,'QA'/1,'A'/1,ampere/1,'q′'/1,'r′'/1,'y′'/1,'z′'/1,'a′'/1,'f′'/1,'p′'/1,'n′'/1,'µ′'/1,'m′'/1,'c′'/1,'d′'/1,'da′'/1,'h′'/1,'k′'/1,'M′'/1,'G′'/1,'T′'/1,'P′'/1,'E′'/1,'Z′'/1,'Y′'/1,'R′'/1,'Q′'/1,′ / 1,arcminute/1,qrad/1,rrad/1,yrad/1,zrad/1,arad/1,frad/1,prad/1,nrad/1,µrad/1,mrad/1,crad/1,drad/1,darad/1,hrad/1,krad/1,'Mrad'/1,'Grad'/1,'Trad'/1,'Prad'/1,'Erad'/1,'Zrad'/1,'Yrad'/1,'Rrad'/1,'Qrad'/1,rad/1,radian/1,qcd/1,rcd/1,ycd/1,zcd/1,acd/1,fcd/1,pcd/1,ncd/1,µcd/1,mcd/1,ccd/1,dcd/1,dacd/1,hcd/1,kcd/1,'Mcd'/1,'Gcd'/1,'Tcd'/1,'Pcd'/1,'Ecd'/1,'Zcd'/1,'Ycd'/1,'Rcd'/1,'Qcd'/1,cd/1,candela/1,qBq/1,rBq/1,yBq/1,zBq/1,aBq/1,fBq/1,pBq/1,nBq/1,µBq/1,mBq/1,cBq/1,dBq/1,daBq/1,hBq/1,kBq/1,'MBq'/1,'GBq'/1,'TBq'/1,'PBq'/1,'EBq'/1,'ZBq'/1,'YBq'/1,'RBq'/1,'QBq'/1,'Bq'/1,becquerel/1,qsr/1,rsr/1,ysr/1,zsr/1,asr/1,fsr/1,psr/1,nsr/1,µsr/1,msr/1,csr/1,dsr/1,dasr/1,hsr/1,ksr/1,'Msr'/1,'Gsr'/1,'Tsr'/1,'Psr'/1,'Esr'/1,'Zsr'/1,'Ysr'/1,'Rsr'/1,'Qsr'/1,sr/1,steradian/1,qSv/1,rSv/1,ySv/1,zSv/1,aSv/1,fSv/1,pSv/1,nSv/1,µSv/1,mSv/1,cSv/1,dSv/1,daSv/1,hSv/1,kSv/1,'MSv'/1,'GSv'/1,'TSv'/1,'PSv'/1,'ESv'/1,'ZSv'/1,'YSv'/1,'RSv'/1,'QSv'/1,'Sv'/1,sievert/1,qGy/1,rGy/1,yGy/1,zGy/1,aGy/1,fGy/1,pGy/1,nGy/1,µGy/1,mGy/1,cGy/1,dGy/1,daGy/1,hGy/1,kGy/1,'MGy'/1,'GGy'/1,'TGy'/1,'PGy'/1,'EGy'/1,'ZGy'/1,'YGy'/1,'RGy'/1,'QGy'/1,'Gy'/1,gray/1,'q°'/1,'r°'/1,'y°'/1,'z°'/1,'a°'/1,'f°'/1,'p°'/1,'n°'/1,'µ°'/1,'m°'/1,'c°'/1,'d°'/1,'da°'/1,'h°'/1,'k°'/1,'M°'/1,'G°'/1,'T°'/1,'P°'/1,'E°'/1,'Z°'/1,'Y°'/1,'R°'/1,'Q°'/1,° / 1,degree/1,'q℃'/1,'r℃'/1,'y℃'/1,'z℃'/1,'a℃'/1,'f℃'/1,'p℃'/1,'n℃'/1,'µ℃'/1,'m℃'/1,'c℃'/1,'d℃'/1,'da℃'/1,'h℃'/1,'k℃'/1,'M℃'/1,'G℃'/1,'T℃'/1,'P℃'/1,'E℃'/1,'Z℃'/1,'Y℃'/1,'R℃'/1,'Q℃'/1,℃ / 1,degree_Celsius/1,qau/1,rau/1,yau/1,zau/1,aau/1,fau/1,pau/1,nau/1,µau/1,mau/1,cau/1,dau/1,daau/1,hau/1,kau/1,'Mau'/1,'Gau'/1,'Tau'/1,'Pau'/1,'Eau'/1,'Zau'/1,'Yau'/1,'Rau'/1,'Qau'/1,au/1,astronomical_unit/1,qd/1,zd/1,ad/1,fd/1,pd/1,nd/1,µd/1,md/1,dd/1,dad/1,hd/1,kd/1,'Md'/1,'Gd'/1,'Td'/1,'Pd'/1,'Ed'/1,'Zd'/1,'Yd'/1,'Rd'/1,'Qd'/1,d/1,day/1,qmin/1,rmin/1,ymin/1,zmin/1,amin/1,fmin/1,pmin/1,nmin/1,µmin/1,mmin/1,cmin/1,dmin/1,damin/1,hmin/1,kmin/1,'Mmin'/1,'Gmin'/1,'Tmin'/1,'Pmin'/1,'Emin'/1,'Zmin'/1,'Ymin'/1,'Rmin'/1,'Qmin'/1,min/1,minute/1,qPa/1,rPa/1,yPa/1,zPa/1,aPa/1,fPa/1,pPa/1,nPa/1,µPa/1,mPa/1,cPa/1,dPa/1,daPa/1,hPa/1,kPa/1,'MPa'/1,'GPa'/1,'TPa'/1,'PPa'/1,'EPa'/1,'ZPa'/1,'YPa'/1,'RPa'/1,'QPa'/1,'Pa'/1,pascal/1,qN/1,rN/1,yN/1,zN/1,aN/1,fN/1,pN/1,nN/1,µN/1,mN/1,cN/1,dN/1,daN/1,hN/1,kN/1,'MN'/1,'GN'/1,'TN'/1,'PN'/1,'EN'/1,'ZN'/1,'YN'/1,'RN'/1,'QN'/1,'N'/1,newton/1,qV/1,rV/1,yV/1,zV/1,aV/1,fV/1,pV/1,nV/1,µV/1,mV/1,cV/1,dV/1,daV/1,hV/1,kV/1,'MV'/1,'GV'/1,'TV'/1,'PV'/1,'EV'/1,'ZV'/1,'YV'/1,'RV'/1,'QV'/1,'V'/1,volt/1,qF/1,rF/1,yF/1,zF/1,aF/1,fF/1,pF/1,nF/1,µF/1,mF/1,cF/1,dF/1,daF/1,hF/1,kF/1,'MF'/1,'GF'/1,'TF'/1,'PF'/1,'EF'/1,'ZF'/1,'YF'/1,'RF'/1,'QF'/1,'F'/1,farad/1,qΩ/1,rΩ/1,yΩ/1,zΩ/1,aΩ/1,fΩ/1,pΩ/1,nΩ/1,µΩ/1,mΩ/1,cΩ/1,dΩ/1,daΩ/1,hΩ/1,kΩ/1,'MΩ'/1,'GΩ'/1,'TΩ'/1,'PΩ'/1,'EΩ'/1,'ZΩ'/1,'YΩ'/1,'RΩ'/1,'QΩ'/1,'Ω'/1,ohm/1,qe/1,re/1,ye/1,ze/1,ae/1,fe/1,pe/1,ne/1,µe/1,me/1,ce/1,de/1,dae/1,he/1,ke/1,'Me'/1,'Ge'/1,'Te'/1,'Pe'/1,'Ee'/1,'Ze'/1,'Ye'/1,'Re'/1,'Qe'/1,e/1,elementary_charge/1,qS/1,rS/1,yS/1,zS/1,aS/1,fS/1,pS/1,nS/1,µS/1,mS/1,cS/1,dS/1,daS/1,hS/1,kS/1,'MS'/1,'GS'/1,'TS'/1,'PS'/1,'ES'/1,'ZS'/1,'YS'/1,'RS'/1,'QS'/1,'S'/1,siemens/1,qWb/1,rWb/1,yWb/1,zWb/1,aWb/1,fWb/1,pWb/1,nWb/1,µWb/1,mWb/1,cWb/1,dWb/1,daWb/1,hWb/1,kWb/1,'MWb'/1,'GWb'/1,'TWb'/1,'PWb'/1,'EWb'/1,'ZWb'/1,'YWb'/1,'RWb'/1,'QWb'/1,'Wb'/1,weber/1,qT/1,rT/1,yT/1,zT/1,aT/1,fT/1,pT/1,nT/1,µT/1,mT/1,cT/1,dT/1,daT/1,hT/1,kT/1,'MT'/1,'GT'/1,'TT'/1,'PT'/1,'ET'/1,'ZT'/1,'YT'/1,'RT'/1,'QT'/1,'T'/1,tesla/1,qlx/1,rlx/1,ylx/1,zlx/1,alx/1,flx/1,plx/1,nlx/1,µlx/1,mlx/1,clx/1,dlx/1,dalx/1,hlx/1,klx/1,'Mlx'/1,'Glx'/1,'Tlx'/1,'Plx'/1,'Elx'/1,'Zlx'/1,'Ylx'/1,'Rlx'/1,'Qlx'/1,lx/1,lux/1,qkat/1,rkat/1,ykat/1,zkat/1,akat/1,fkat/1,pkat/1,nkat/1,µkat/1,mkat/1,ckat/1,dkat/1,dakat/1,hkat/1,kkat/1,'Mkat'/1,'Gkat'/1,'Tkat'/1,'Pkat'/1,'Ekat'/1,'Zkat'/1,'Ykat'/1,'Rkat'/1,'Qkat'/1,kat/1,katal/1,qHz/1,rHz/1,yHz/1,zHz/1,aHz/1,fHz/1,pHz/1,nHz/1,µHz/1,mHz/1,cHz/1,dHz/1,daHz/1,hHz/1,kHz/1,'MHz'/1,'GHz'/1,'THz'/1,'PHz'/1,'EHz'/1,'ZHz'/1,'YHz'/1,'RHz'/1,'QHz'/1,'Hz'/1,hertz/1,qℎ/1,rℎ/1,yℎ/1,zℎ/1,aℎ/1,fℎ/1,pℎ/1,nℎ/1,µℎ/1,mℎ/1,cℎ/1,dℎ/1,daℎ/1,hℎ/1,kℎ/1,'Mℎ'/1,'Gℎ'/1,'Tℎ'/1,'Pℎ'/1,'Eℎ'/1,'Zℎ'/1,'Yℎ'/1,'Rℎ'/1,'Qℎ'/1,ℎ/1,planck_constant/1,qW/1,rW/1,yW/1,zW/1,aW/1,fW/1,pW/1,nW/1,µW/1,mW/1,cW/1,dW/1,daW/1,hW/1,kW/1,'MW'/1,'GW'/1,'TW'/1,'PW'/1,'EW'/1,'ZW'/1,'YW'/1,'RW'/1,'QW'/1,'W'/1,watt/1,qh/1,rh/1,yh/1,zh/1,ah/1,fh/1,ph/1,nh/1,µh/1,mh/1,dh/1,dah/1,hh/1,kh/1,'Mh'/1,'Gh'/1,'Th'/1,'Ph'/1,'Eh'/1,'Zh'/1,'Yh'/1,'Rh'/1,'Qh'/1,h/1,hour/1,qΔν_Cs/1,rΔν_Cs/1,yΔν_Cs/1,zΔν_Cs/1,aΔν_Cs/1,fΔν_Cs/1,pΔν_Cs/1,nΔν_Cs/1,µΔν_Cs/1,mΔν_Cs/1,cΔν_Cs/1,dΔν_Cs/1,daΔν_Cs/1,hΔν_Cs/1,kΔν_Cs/1,'MΔν_Cs'/1,'GΔν_Cs'/1,'TΔν_Cs'/1,'PΔν_Cs'/1,'EΔν_Cs'/1,'ZΔν_Cs'/1,'YΔν_Cs'/1,'RΔν_Cs'/1,'QΔν_Cs'/1,'Δν_Cs'/1,hyperfine_structure_transition_frequency_of_cs/1,qg/1,rg/1,yg/1,zg/1,ag/1,fg/1,pg/1,ng/1,µg/1,mg/1,cg/1,dg/1,dag/1,hg/1,kg/1,'Mg'/1,'Gg'/1,'Tg'/1,'Pg'/1,'Eg'/1,'Zg'/1,'Yg'/1,'Rg'/1,'Qg'/1,g/1,gram/1,qN_A/1,rN_A/1,yN_A/1,zN_A/1,aN_A/1,fN_A/1,pN_A/1,nN_A/1,µN_A/1,mN_A/1,cN_A/1,dN_A/1,daN_A/1,hN_A/1,kN_A/1,'MN_A'/1,'GN_A'/1,'TN_A'/1,'PN_A'/1,'EN_A'/1,'ZN_A'/1,'YN_A'/1,'RN_A'/1,'QN_A'/1,'N_A'/1,avogadro_constant/1,qmol/1,rmol/1,ymol/1,zmol/1,amol/1,fmol/1,pmol/1,nmol/1,µmol/1,mmol/1,cmol/1,dmol/1,damol/1,hmol/1,kmol/1,'Mmol'/1,'Gmol'/1,'Tmol'/1,'Pmol'/1,'Emol'/1,'Zmol'/1,'Ymol'/1,'Rmol'/1,'Qmol'/1,mol/1,mole/1,qK_cd/1,rK_cd/1,yK_cd/1,zK_cd/1,aK_cd/1,fK_cd/1,pK_cd/1,nK_cd/1,µK_cd/1,mK_cd/1,cK_cd/1,dK_cd/1,daK_cd/1,hK_cd/1,kK_cd/1,'MK_cd'/1,'GK_cd'/1,'TK_cd'/1,'PK_cd'/1,'EK_cd'/1,'ZK_cd'/1,'YK_cd'/1,'RK_cd'/1,'QK_cd'/1,'K_cd'/1,luminous_efficacy/1,qC/1,rC/1,yC/1,zC/1,aC/1,fC/1,pC/1,nC/1,µC/1,mC/1,cC/1,dC/1,daC/1,hC/1,kC/1,'MC'/1,'GC'/1,'TC'/1,'PC'/1,'EC'/1,'ZC'/1,'YC'/1,'RC'/1,'QC'/1,'C'/1,coulomb/1,qk/1,rk/1,yk/1,zk/1,ak/1,fk/1,nk/1,µk/1,mk/1,ck/1,dk/1,dak/1,hk/1,kk/1,'Mk'/1,'Gk'/1,'Tk'/1,'Pk'/1,'Ek'/1,'Zk'/1,'Yk'/1,'Rk'/1,'Qk'/1,k/1,boltzmann_constant/1,'qμ₀'/1,'rμ₀'/1,'yμ₀'/1,'zμ₀'/1,'aμ₀'/1,'fμ₀'/1,'pμ₀'/1,'nμ₀'/1,'µμ₀'/1,'mμ₀'/1,'cμ₀'/1,'dμ₀'/1,'daμ₀'/1,'hμ₀'/1,'kμ₀'/1,'Mμ₀'/1,'Gμ₀'/1,'Tμ₀'/1,'Pμ₀'/1,'Eμ₀'/1,'Zμ₀'/1,'Yμ₀'/1,'Rμ₀'/1,'Qμ₀'/1,'μ₀'/1,magnetic_constant/1,qc/1,rc/1,yc/1,zc/1,ac/1,fc/1,nc/1,µc/1,mc/1,cc/1,dc/1,dac/1,hc/1,kc/1,'Mc'/1,'Gc'/1,'Tc'/1,'Pc'/1,'Ec'/1,'Zc'/1,'Yc'/1,'Rc'/1,'Qc'/1,c/1,speed_of_light_in_vacuum/1]).
qK(:(si,quecto(:(si,kelvin)))).
rK(:(si,ronto(:(si,kelvin)))).
yK(:(si,yocto(:(si,kelvin)))).
zK(:(si,zepto(:(si,kelvin)))).
aK(:(si,atto(:(si,kelvin)))).
fK(:(si,femto(:(si,kelvin)))).
pK(:(si,pico(:(si,kelvin)))).
nK(:(si,nano(:(si,kelvin)))).
µK(:(si,micro(:(si,kelvin)))).
mK(:(si,milli(:(si,kelvin)))).
cK(:(si,centi(:(si,kelvin)))).
dK(:(si,deci(:(si,kelvin)))).
daK(:(si,deca(:(si,kelvin)))).
hK(:(si,hecto(:(si,kelvin)))).
kK(:(si,kilo(:(si,kelvin)))).
'MK'(:(si,mega(:(si,kelvin)))).
'GK'(:(si,giga(:(si,kelvin)))).
'TK'(:(si,tera(:(si,kelvin)))).
'PK'(:(si,peta(:(si,kelvin)))).
'EK'(:(si,exa(:(si,kelvin)))).
'ZK'(:(si,zetta(:(si,kelvin)))).
'YK'(:(si,yotta(:(si,kelvin)))).
'RK'(:(si,ronna(:(si,kelvin)))).
'QK'(:(si,quetta(:(si,kelvin)))).
'K'(:(si,kelvin)).
kelvin(:(si,kelvin)).
qJ(:(si,quecto(:(si,joule)))).
rJ(:(si,ronto(:(si,joule)))).
yJ(:(si,yocto(:(si,joule)))).
zJ(:(si,zepto(:(si,joule)))).
aJ(:(si,atto(:(si,joule)))).
fJ(:(si,femto(:(si,joule)))).
pJ(:(si,pico(:(si,joule)))).
nJ(:(si,nano(:(si,joule)))).
µJ(:(si,micro(:(si,joule)))).
mJ(:(si,milli(:(si,joule)))).
cJ(:(si,centi(:(si,joule)))).
dJ(:(si,deci(:(si,joule)))).
daJ(:(si,deca(:(si,joule)))).
hJ(:(si,hecto(:(si,joule)))).
kJ(:(si,kilo(:(si,joule)))).
'MJ'(:(si,mega(:(si,joule)))).
'GJ'(:(si,giga(:(si,joule)))).
'TJ'(:(si,tera(:(si,joule)))).
'PJ'(:(si,peta(:(si,joule)))).
'EJ'(:(si,exa(:(si,joule)))).
'ZJ'(:(si,zetta(:(si,joule)))).
'YJ'(:(si,yotta(:(si,joule)))).
'RJ'(:(si,ronna(:(si,joule)))).
'QJ'(:(si,quetta(:(si,joule)))).
'J'(:(si,joule)).
joule(:(si,joule)).
qH(:(si,quecto(:(si,henry)))).
rH(:(si,ronto(:(si,henry)))).
yH(:(si,yocto(:(si,henry)))).
zH(:(si,zepto(:(si,henry)))).
aH(:(si,atto(:(si,henry)))).
fH(:(si,femto(:(si,henry)))).
pH(:(si,pico(:(si,henry)))).
nH(:(si,nano(:(si,henry)))).
µH(:(si,micro(:(si,henry)))).
mH(:(si,milli(:(si,henry)))).
cH(:(si,centi(:(si,henry)))).
dH(:(si,deci(:(si,henry)))).
daH(:(si,deca(:(si,henry)))).
hH(:(si,hecto(:(si,henry)))).
kH(:(si,kilo(:(si,henry)))).
'MH'(:(si,mega(:(si,henry)))).
'GH'(:(si,giga(:(si,henry)))).
'TH'(:(si,tera(:(si,henry)))).
'PH'(:(si,peta(:(si,henry)))).
'EH'(:(si,exa(:(si,henry)))).
'ZH'(:(si,zetta(:(si,henry)))).
'YH'(:(si,yotta(:(si,henry)))).
'RH'(:(si,ronna(:(si,henry)))).
'QH'(:(si,quetta(:(si,henry)))).
'H'(:(si,henry)).
henry(:(si,henry)).
qm(:(si,quecto(:(si,metre)))).
rm(:(si,ronto(:(si,metre)))).
ym(:(si,yocto(:(si,metre)))).
zm(:(si,zepto(:(si,metre)))).
am(:(si,atto(:(si,metre)))).
fm(:(si,femto(:(si,metre)))).
pm(:(si,pico(:(si,metre)))).
nm(:(si,nano(:(si,metre)))).
µm(:(si,micro(:(si,metre)))).
mm(:(si,milli(:(si,metre)))).
cm(:(si,centi(:(si,metre)))).
dm(:(si,deci(:(si,metre)))).
dam(:(si,deca(:(si,metre)))).
hm(:(si,hecto(:(si,metre)))).
km(:(si,kilo(:(si,metre)))).
'Mm'(:(si,mega(:(si,metre)))).
'Gm'(:(si,giga(:(si,metre)))).
'Tm'(:(si,tera(:(si,metre)))).
'Pm'(:(si,peta(:(si,metre)))).
'Em'(:(si,exa(:(si,metre)))).
'Zm'(:(si,zetta(:(si,metre)))).
'Ym'(:(si,yotta(:(si,metre)))).
'Rm'(:(si,ronna(:(si,metre)))).
'Qm'(:(si,quetta(:(si,metre)))).
m(:(si,metre)).
metre(:(si,metre)).
qs(:(si,quecto(:(si,second)))).
rs(:(si,ronto(:(si,second)))).
ys(:(si,yocto(:(si,second)))).
zs(:(si,zepto(:(si,second)))).
as(:(si,atto(:(si,second)))).
fs(:(si,femto(:(si,second)))).
ps(:(si,pico(:(si,second)))).
ns(:(si,nano(:(si,second)))).
µs(:(si,micro(:(si,second)))).
ms(:(si,milli(:(si,second)))).
cs(:(si,centi(:(si,second)))).
ds(:(si,deci(:(si,second)))).
das(:(si,deca(:(si,second)))).
hs(:(si,hecto(:(si,second)))).
ks(:(si,kilo(:(si,second)))).
'Ms'(:(si,mega(:(si,second)))).
'Gs'(:(si,giga(:(si,second)))).
'Ts'(:(si,tera(:(si,second)))).
'Ps'(:(si,peta(:(si,second)))).
'Es'(:(si,exa(:(si,second)))).
'Zs'(:(si,zetta(:(si,second)))).
'Ys'(:(si,yotta(:(si,second)))).
'Rs'(:(si,ronna(:(si,second)))).
'Qs'(:(si,quetta(:(si,second)))).
s(:(si,second)).
second(:(si,second)).
'qg₀'(:(si,quecto(:(si,standard_gravity)))).
'rg₀'(:(si,ronto(:(si,standard_gravity)))).
'yg₀'(:(si,yocto(:(si,standard_gravity)))).
'zg₀'(:(si,zepto(:(si,standard_gravity)))).
'ag₀'(:(si,atto(:(si,standard_gravity)))).
'fg₀'(:(si,femto(:(si,standard_gravity)))).
'pg₀'(:(si,pico(:(si,standard_gravity)))).
'ng₀'(:(si,nano(:(si,standard_gravity)))).
'µg₀'(:(si,micro(:(si,standard_gravity)))).
'mg₀'(:(si,milli(:(si,standard_gravity)))).
'cg₀'(:(si,centi(:(si,standard_gravity)))).
'dg₀'(:(si,deci(:(si,standard_gravity)))).
'dag₀'(:(si,deca(:(si,standard_gravity)))).
'hg₀'(:(si,hecto(:(si,standard_gravity)))).
'kg₀'(:(si,kilo(:(si,standard_gravity)))).
'Mg₀'(:(si,mega(:(si,standard_gravity)))).
'Gg₀'(:(si,giga(:(si,standard_gravity)))).
'Tg₀'(:(si,tera(:(si,standard_gravity)))).
'Pg₀'(:(si,peta(:(si,standard_gravity)))).
'Eg₀'(:(si,exa(:(si,standard_gravity)))).
'Zg₀'(:(si,zetta(:(si,standard_gravity)))).
'Yg₀'(:(si,yotta(:(si,standard_gravity)))).
'Rg₀'(:(si,ronna(:(si,standard_gravity)))).
'Qg₀'(:(si,quetta(:(si,standard_gravity)))).
'g₀'(:(si,standard_gravity)).
standard_gravity(:(si,standard_gravity)).
qlm(:(si,quecto(:(si,lumen)))).
rlm(:(si,ronto(:(si,lumen)))).
ylm(:(si,yocto(:(si,lumen)))).
zlm(:(si,zepto(:(si,lumen)))).
alm(:(si,atto(:(si,lumen)))).
flm(:(si,femto(:(si,lumen)))).
plm(:(si,pico(:(si,lumen)))).
nlm(:(si,nano(:(si,lumen)))).
µlm(:(si,micro(:(si,lumen)))).
mlm(:(si,milli(:(si,lumen)))).
clm(:(si,centi(:(si,lumen)))).
dlm(:(si,deci(:(si,lumen)))).
dalm(:(si,deca(:(si,lumen)))).
hlm(:(si,hecto(:(si,lumen)))).
klm(:(si,kilo(:(si,lumen)))).
'Mlm'(:(si,mega(:(si,lumen)))).
'Glm'(:(si,giga(:(si,lumen)))).
'Tlm'(:(si,tera(:(si,lumen)))).
'Plm'(:(si,peta(:(si,lumen)))).
'Elm'(:(si,exa(:(si,lumen)))).
'Zlm'(:(si,zetta(:(si,lumen)))).
'Ylm'(:(si,yotta(:(si,lumen)))).
'Rlm'(:(si,ronna(:(si,lumen)))).
'Qlm'(:(si,quetta(:(si,lumen)))).
lm(:(si,lumen)).
lumen(:(si,lumen)).
qeV(:(si,quecto(:(si,electronvolt)))).
reV(:(si,ronto(:(si,electronvolt)))).
yeV(:(si,yocto(:(si,electronvolt)))).
zeV(:(si,zepto(:(si,electronvolt)))).
aeV(:(si,atto(:(si,electronvolt)))).
feV(:(si,femto(:(si,electronvolt)))).
peV(:(si,pico(:(si,electronvolt)))).
neV(:(si,nano(:(si,electronvolt)))).
µeV(:(si,micro(:(si,electronvolt)))).
meV(:(si,milli(:(si,electronvolt)))).
ceV(:(si,centi(:(si,electronvolt)))).
deV(:(si,deci(:(si,electronvolt)))).
daeV(:(si,deca(:(si,electronvolt)))).
heV(:(si,hecto(:(si,electronvolt)))).
keV(:(si,kilo(:(si,electronvolt)))).
'MeV'(:(si,mega(:(si,electronvolt)))).
'GeV'(:(si,giga(:(si,electronvolt)))).
'TeV'(:(si,tera(:(si,electronvolt)))).
'PeV'(:(si,peta(:(si,electronvolt)))).
'EeV'(:(si,exa(:(si,electronvolt)))).
'ZeV'(:(si,zetta(:(si,electronvolt)))).
'YeV'(:(si,yotta(:(si,electronvolt)))).
'ReV'(:(si,ronna(:(si,electronvolt)))).
'QeV'(:(si,quetta(:(si,electronvolt)))).
eV(:(si,electronvolt)).
electronvolt(:(si,electronvolt)).
qDa(:(si,quecto(:(si,dalton)))).
rDa(:(si,ronto(:(si,dalton)))).
yDa(:(si,yocto(:(si,dalton)))).
zDa(:(si,zepto(:(si,dalton)))).
aDa(:(si,atto(:(si,dalton)))).
fDa(:(si,femto(:(si,dalton)))).
pDa(:(si,pico(:(si,dalton)))).
nDa(:(si,nano(:(si,dalton)))).
µDa(:(si,micro(:(si,dalton)))).
mDa(:(si,milli(:(si,dalton)))).
cDa(:(si,centi(:(si,dalton)))).
dDa(:(si,deci(:(si,dalton)))).
daDa(:(si,deca(:(si,dalton)))).
hDa(:(si,hecto(:(si,dalton)))).
kDa(:(si,kilo(:(si,dalton)))).
'MDa'(:(si,mega(:(si,dalton)))).
'GDa'(:(si,giga(:(si,dalton)))).
'TDa'(:(si,tera(:(si,dalton)))).
'PDa'(:(si,peta(:(si,dalton)))).
'EDa'(:(si,exa(:(si,dalton)))).
'ZDa'(:(si,zetta(:(si,dalton)))).
'YDa'(:(si,yotta(:(si,dalton)))).
'RDa'(:(si,ronna(:(si,dalton)))).
'QDa'(:(si,quetta(:(si,dalton)))).
'Da'(:(si,dalton)).
dalton(:(si,dalton)).
rt(:(si,ronto(:(si,tonne)))).
yt(:(si,yocto(:(si,tonne)))).
zt(:(si,zepto(:(si,tonne)))).
at(:(si,atto(:(si,tonne)))).
nt(:(si,nano(:(si,tonne)))).
µt(:(si,micro(:(si,tonne)))).
mt(:(si,milli(:(si,tonne)))).
ct(:(si,centi(:(si,tonne)))).
dt(:(si,deci(:(si,tonne)))).
dat(:(si,deca(:(si,tonne)))).
ht(:(si,hecto(:(si,tonne)))).
kt(:(si,kilo(:(si,tonne)))).
'Mt'(:(si,mega(:(si,tonne)))).
'Gt'(:(si,giga(:(si,tonne)))).
'Tt'(:(si,tera(:(si,tonne)))).
'Pt'(:(si,peta(:(si,tonne)))).
'Et'(:(si,exa(:(si,tonne)))).
'Zt'(:(si,zetta(:(si,tonne)))).
'Yt'(:(si,yotta(:(si,tonne)))).
'Rt'(:(si,ronna(:(si,tonne)))).
'Qt'(:(si,quetta(:(si,tonne)))).
t(:(si,tonne)).
tonne(:(si,tonne)).
qL(:(si,quecto(:(si,litre)))).
rL(:(si,ronto(:(si,litre)))).
yL(:(si,yocto(:(si,litre)))).
zL(:(si,zepto(:(si,litre)))).
aL(:(si,atto(:(si,litre)))).
fL(:(si,femto(:(si,litre)))).
pL(:(si,pico(:(si,litre)))).
nL(:(si,nano(:(si,litre)))).
µL(:(si,micro(:(si,litre)))).
mL(:(si,milli(:(si,litre)))).
cL(:(si,centi(:(si,litre)))).
dL(:(si,deci(:(si,litre)))).
daL(:(si,deca(:(si,litre)))).
hL(:(si,hecto(:(si,litre)))).
kL(:(si,kilo(:(si,litre)))).
'ML'(:(si,mega(:(si,litre)))).
'GL'(:(si,giga(:(si,litre)))).
'TL'(:(si,tera(:(si,litre)))).
'PL'(:(si,peta(:(si,litre)))).
'EL'(:(si,exa(:(si,litre)))).
'ZL'(:(si,zetta(:(si,litre)))).
'YL'(:(si,yotta(:(si,litre)))).
'RL'(:(si,ronna(:(si,litre)))).
'QL'(:(si,quetta(:(si,litre)))).
'L'(:(si,litre)).
litre(:(si,litre)).
qa(:(si,quecto(:(si,are)))).
ra(:(si,ronto(:(si,are)))).
ya(:(si,yocto(:(si,are)))).
za(:(si,zepto(:(si,are)))).
aa(:(si,atto(:(si,are)))).
fa(:(si,femto(:(si,are)))).
pa(:(si,pico(:(si,are)))).
na(:(si,nano(:(si,are)))).
µa(:(si,micro(:(si,are)))).
ma(:(si,milli(:(si,are)))).
ca(:(si,centi(:(si,are)))).
da(:(si,deci(:(si,are)))).
daa(:(si,deca(:(si,are)))).
ha(:(si,hecto(:(si,are)))).
ka(:(si,kilo(:(si,are)))).
'Ma'(:(si,mega(:(si,are)))).
'Ga'(:(si,giga(:(si,are)))).
'Ta'(:(si,tera(:(si,are)))).
'Ea'(:(si,exa(:(si,are)))).
'Za'(:(si,zetta(:(si,are)))).
'Ya'(:(si,yotta(:(si,are)))).
'Ra'(:(si,ronna(:(si,are)))).
'Qa'(:(si,quetta(:(si,are)))).
a(:(si,are)).
are(:(si,are)).
'q″'(:(si,quecto(:(si,arcsecond)))).
'r″'(:(si,ronto(:(si,arcsecond)))).
'y″'(:(si,yocto(:(si,arcsecond)))).
'z″'(:(si,zepto(:(si,arcsecond)))).
'a″'(:(si,atto(:(si,arcsecond)))).
'f″'(:(si,femto(:(si,arcsecond)))).
'p″'(:(si,pico(:(si,arcsecond)))).
'n″'(:(si,nano(:(si,arcsecond)))).
'µ″'(:(si,micro(:(si,arcsecond)))).
'm″'(:(si,milli(:(si,arcsecond)))).
'c″'(:(si,centi(:(si,arcsecond)))).
'd″'(:(si,deci(:(si,arcsecond)))).
'da″'(:(si,deca(:(si,arcsecond)))).
'h″'(:(si,hecto(:(si,arcsecond)))).
'k″'(:(si,kilo(:(si,arcsecond)))).
'M″'(:(si,mega(:(si,arcsecond)))).
'G″'(:(si,giga(:(si,arcsecond)))).
'T″'(:(si,tera(:(si,arcsecond)))).
'P″'(:(si,peta(:(si,arcsecond)))).
'E″'(:(si,exa(:(si,arcsecond)))).
'Z″'(:(si,zetta(:(si,arcsecond)))).
'Y″'(:(si,yotta(:(si,arcsecond)))).
'R″'(:(si,ronna(:(si,arcsecond)))).
'Q″'(:(si,quetta(:(si,arcsecond)))).
″(:(si,arcsecond)).
arcsecond(:(si,arcsecond)).
qA(:(si,quecto(:(si,ampere)))).
rA(:(si,ronto(:(si,ampere)))).
yA(:(si,yocto(:(si,ampere)))).
zA(:(si,zepto(:(si,ampere)))).
aA(:(si,atto(:(si,ampere)))).
fA(:(si,femto(:(si,ampere)))).
pA(:(si,pico(:(si,ampere)))).
nA(:(si,nano(:(si,ampere)))).
µA(:(si,micro(:(si,ampere)))).
mA(:(si,milli(:(si,ampere)))).
cA(:(si,centi(:(si,ampere)))).
dA(:(si,deci(:(si,ampere)))).
daA(:(si,deca(:(si,ampere)))).
hA(:(si,hecto(:(si,ampere)))).
kA(:(si,kilo(:(si,ampere)))).
'MA'(:(si,mega(:(si,ampere)))).
'GA'(:(si,giga(:(si,ampere)))).
'TA'(:(si,tera(:(si,ampere)))).
'PA'(:(si,peta(:(si,ampere)))).
'EA'(:(si,exa(:(si,ampere)))).
'ZA'(:(si,zetta(:(si,ampere)))).
'YA'(:(si,yotta(:(si,ampere)))).
'RA'(:(si,ronna(:(si,ampere)))).
'QA'(:(si,quetta(:(si,ampere)))).
'A'(:(si,ampere)).
ampere(:(si,ampere)).
'q′'(:(si,quecto(:(si,arcminute)))).
'r′'(:(si,ronto(:(si,arcminute)))).
'y′'(:(si,yocto(:(si,arcminute)))).
'z′'(:(si,zepto(:(si,arcminute)))).
'a′'(:(si,atto(:(si,arcminute)))).
'f′'(:(si,femto(:(si,arcminute)))).
'p′'(:(si,pico(:(si,arcminute)))).
'n′'(:(si,nano(:(si,arcminute)))).
'µ′'(:(si,micro(:(si,arcminute)))).
'm′'(:(si,milli(:(si,arcminute)))).
'c′'(:(si,centi(:(si,arcminute)))).
'd′'(:(si,deci(:(si,arcminute)))).
'da′'(:(si,deca(:(si,arcminute)))).
'h′'(:(si,hecto(:(si,arcminute)))).
'k′'(:(si,kilo(:(si,arcminute)))).
'M′'(:(si,mega(:(si,arcminute)))).
'G′'(:(si,giga(:(si,arcminute)))).
'T′'(:(si,tera(:(si,arcminute)))).
'P′'(:(si,peta(:(si,arcminute)))).
'E′'(:(si,exa(:(si,arcminute)))).
'Z′'(:(si,zetta(:(si,arcminute)))).
'Y′'(:(si,yotta(:(si,arcminute)))).
'R′'(:(si,ronna(:(si,arcminute)))).
'Q′'(:(si,quetta(:(si,arcminute)))).
′(:(si,arcminute)).
arcminute(:(si,arcminute)).
qrad(:(si,quecto(:(si,radian)))).
rrad(:(si,ronto(:(si,radian)))).
yrad(:(si,yocto(:(si,radian)))).
zrad(:(si,zepto(:(si,radian)))).
arad(:(si,atto(:(si,radian)))).
frad(:(si,femto(:(si,radian)))).
prad(:(si,pico(:(si,radian)))).
nrad(:(si,nano(:(si,radian)))).
µrad(:(si,micro(:(si,radian)))).
mrad(:(si,milli(:(si,radian)))).
crad(:(si,centi(:(si,radian)))).
drad(:(si,deci(:(si,radian)))).
darad(:(si,deca(:(si,radian)))).
hrad(:(si,hecto(:(si,radian)))).
krad(:(si,kilo(:(si,radian)))).
'Mrad'(:(si,mega(:(si,radian)))).
'Grad'(:(si,giga(:(si,radian)))).
'Trad'(:(si,tera(:(si,radian)))).
'Prad'(:(si,peta(:(si,radian)))).
'Erad'(:(si,exa(:(si,radian)))).
'Zrad'(:(si,zetta(:(si,radian)))).
'Yrad'(:(si,yotta(:(si,radian)))).
'Rrad'(:(si,ronna(:(si,radian)))).
'Qrad'(:(si,quetta(:(si,radian)))).
rad(:(si,radian)).
radian(:(si,radian)).
qcd(:(si,quecto(:(si,candela)))).
rcd(:(si,ronto(:(si,candela)))).
ycd(:(si,yocto(:(si,candela)))).
zcd(:(si,zepto(:(si,candela)))).
acd(:(si,atto(:(si,candela)))).
fcd(:(si,femto(:(si,candela)))).
pcd(:(si,pico(:(si,candela)))).
ncd(:(si,nano(:(si,candela)))).
µcd(:(si,micro(:(si,candela)))).
mcd(:(si,milli(:(si,candela)))).
ccd(:(si,centi(:(si,candela)))).
dcd(:(si,deci(:(si,candela)))).
dacd(:(si,deca(:(si,candela)))).
hcd(:(si,hecto(:(si,candela)))).
kcd(:(si,kilo(:(si,candela)))).
'Mcd'(:(si,mega(:(si,candela)))).
'Gcd'(:(si,giga(:(si,candela)))).
'Tcd'(:(si,tera(:(si,candela)))).
'Pcd'(:(si,peta(:(si,candela)))).
'Ecd'(:(si,exa(:(si,candela)))).
'Zcd'(:(si,zetta(:(si,candela)))).
'Ycd'(:(si,yotta(:(si,candela)))).
'Rcd'(:(si,ronna(:(si,candela)))).
'Qcd'(:(si,quetta(:(si,candela)))).
cd(:(si,candela)).
candela(:(si,candela)).
qBq(:(si,quecto(:(si,becquerel)))).
rBq(:(si,ronto(:(si,becquerel)))).
yBq(:(si,yocto(:(si,becquerel)))).
zBq(:(si,zepto(:(si,becquerel)))).
aBq(:(si,atto(:(si,becquerel)))).
fBq(:(si,femto(:(si,becquerel)))).
pBq(:(si,pico(:(si,becquerel)))).
nBq(:(si,nano(:(si,becquerel)))).
µBq(:(si,micro(:(si,becquerel)))).
mBq(:(si,milli(:(si,becquerel)))).
cBq(:(si,centi(:(si,becquerel)))).
dBq(:(si,deci(:(si,becquerel)))).
daBq(:(si,deca(:(si,becquerel)))).
hBq(:(si,hecto(:(si,becquerel)))).
kBq(:(si,kilo(:(si,becquerel)))).
'MBq'(:(si,mega(:(si,becquerel)))).
'GBq'(:(si,giga(:(si,becquerel)))).
'TBq'(:(si,tera(:(si,becquerel)))).
'PBq'(:(si,peta(:(si,becquerel)))).
'EBq'(:(si,exa(:(si,becquerel)))).
'ZBq'(:(si,zetta(:(si,becquerel)))).
'YBq'(:(si,yotta(:(si,becquerel)))).
'RBq'(:(si,ronna(:(si,becquerel)))).
'QBq'(:(si,quetta(:(si,becquerel)))).
'Bq'(:(si,becquerel)).
becquerel(:(si,becquerel)).
qsr(:(si,quecto(:(si,steradian)))).
rsr(:(si,ronto(:(si,steradian)))).
ysr(:(si,yocto(:(si,steradian)))).
zsr(:(si,zepto(:(si,steradian)))).
asr(:(si,atto(:(si,steradian)))).
fsr(:(si,femto(:(si,steradian)))).
psr(:(si,pico(:(si,steradian)))).
nsr(:(si,nano(:(si,steradian)))).
µsr(:(si,micro(:(si,steradian)))).
msr(:(si,milli(:(si,steradian)))).
csr(:(si,centi(:(si,steradian)))).
dsr(:(si,deci(:(si,steradian)))).
dasr(:(si,deca(:(si,steradian)))).
hsr(:(si,hecto(:(si,steradian)))).
ksr(:(si,kilo(:(si,steradian)))).
'Msr'(:(si,mega(:(si,steradian)))).
'Gsr'(:(si,giga(:(si,steradian)))).
'Tsr'(:(si,tera(:(si,steradian)))).
'Psr'(:(si,peta(:(si,steradian)))).
'Esr'(:(si,exa(:(si,steradian)))).
'Zsr'(:(si,zetta(:(si,steradian)))).
'Ysr'(:(si,yotta(:(si,steradian)))).
'Rsr'(:(si,ronna(:(si,steradian)))).
'Qsr'(:(si,quetta(:(si,steradian)))).
sr(:(si,steradian)).
steradian(:(si,steradian)).
qSv(:(si,quecto(:(si,sievert)))).
rSv(:(si,ronto(:(si,sievert)))).
ySv(:(si,yocto(:(si,sievert)))).
zSv(:(si,zepto(:(si,sievert)))).
aSv(:(si,atto(:(si,sievert)))).
fSv(:(si,femto(:(si,sievert)))).
pSv(:(si,pico(:(si,sievert)))).
nSv(:(si,nano(:(si,sievert)))).
µSv(:(si,micro(:(si,sievert)))).
mSv(:(si,milli(:(si,sievert)))).
cSv(:(si,centi(:(si,sievert)))).
dSv(:(si,deci(:(si,sievert)))).
daSv(:(si,deca(:(si,sievert)))).
hSv(:(si,hecto(:(si,sievert)))).
kSv(:(si,kilo(:(si,sievert)))).
'MSv'(:(si,mega(:(si,sievert)))).
'GSv'(:(si,giga(:(si,sievert)))).
'TSv'(:(si,tera(:(si,sievert)))).
'PSv'(:(si,peta(:(si,sievert)))).
'ESv'(:(si,exa(:(si,sievert)))).
'ZSv'(:(si,zetta(:(si,sievert)))).
'YSv'(:(si,yotta(:(si,sievert)))).
'RSv'(:(si,ronna(:(si,sievert)))).
'QSv'(:(si,quetta(:(si,sievert)))).
'Sv'(:(si,sievert)).
sievert(:(si,sievert)).
qGy(:(si,quecto(:(si,gray)))).
rGy(:(si,ronto(:(si,gray)))).
yGy(:(si,yocto(:(si,gray)))).
zGy(:(si,zepto(:(si,gray)))).
aGy(:(si,atto(:(si,gray)))).
fGy(:(si,femto(:(si,gray)))).
pGy(:(si,pico(:(si,gray)))).
nGy(:(si,nano(:(si,gray)))).
µGy(:(si,micro(:(si,gray)))).
mGy(:(si,milli(:(si,gray)))).
cGy(:(si,centi(:(si,gray)))).
dGy(:(si,deci(:(si,gray)))).
daGy(:(si,deca(:(si,gray)))).
hGy(:(si,hecto(:(si,gray)))).
kGy(:(si,kilo(:(si,gray)))).
'MGy'(:(si,mega(:(si,gray)))).
'GGy'(:(si,giga(:(si,gray)))).
'TGy'(:(si,tera(:(si,gray)))).
'PGy'(:(si,peta(:(si,gray)))).
'EGy'(:(si,exa(:(si,gray)))).
'ZGy'(:(si,zetta(:(si,gray)))).
'YGy'(:(si,yotta(:(si,gray)))).
'RGy'(:(si,ronna(:(si,gray)))).
'QGy'(:(si,quetta(:(si,gray)))).
'Gy'(:(si,gray)).
gray(:(si,gray)).
'q°'(:(si,quecto(:(si,degree)))).
'r°'(:(si,ronto(:(si,degree)))).
'y°'(:(si,yocto(:(si,degree)))).
'z°'(:(si,zepto(:(si,degree)))).
'a°'(:(si,atto(:(si,degree)))).
'f°'(:(si,femto(:(si,degree)))).
'p°'(:(si,pico(:(si,degree)))).
'n°'(:(si,nano(:(si,degree)))).
'µ°'(:(si,micro(:(si,degree)))).
'm°'(:(si,milli(:(si,degree)))).
'c°'(:(si,centi(:(si,degree)))).
'd°'(:(si,deci(:(si,degree)))).
'da°'(:(si,deca(:(si,degree)))).
'h°'(:(si,hecto(:(si,degree)))).
'k°'(:(si,kilo(:(si,degree)))).
'M°'(:(si,mega(:(si,degree)))).
'G°'(:(si,giga(:(si,degree)))).
'T°'(:(si,tera(:(si,degree)))).
'P°'(:(si,peta(:(si,degree)))).
'E°'(:(si,exa(:(si,degree)))).
'Z°'(:(si,zetta(:(si,degree)))).
'Y°'(:(si,yotta(:(si,degree)))).
'R°'(:(si,ronna(:(si,degree)))).
'Q°'(:(si,quetta(:(si,degree)))).
°(:(si,degree)).
degree(:(si,degree)).
'q℃'(:(si,quecto(:(si,degree_Celsius)))).
'r℃'(:(si,ronto(:(si,degree_Celsius)))).
'y℃'(:(si,yocto(:(si,degree_Celsius)))).
'z℃'(:(si,zepto(:(si,degree_Celsius)))).
'a℃'(:(si,atto(:(si,degree_Celsius)))).
'f℃'(:(si,femto(:(si,degree_Celsius)))).
'p℃'(:(si,pico(:(si,degree_Celsius)))).
'n℃'(:(si,nano(:(si,degree_Celsius)))).
'µ℃'(:(si,micro(:(si,degree_Celsius)))).
'm℃'(:(si,milli(:(si,degree_Celsius)))).
'c℃'(:(si,centi(:(si,degree_Celsius)))).
'd℃'(:(si,deci(:(si,degree_Celsius)))).
'da℃'(:(si,deca(:(si,degree_Celsius)))).
'h℃'(:(si,hecto(:(si,degree_Celsius)))).
'k℃'(:(si,kilo(:(si,degree_Celsius)))).
'M℃'(:(si,mega(:(si,degree_Celsius)))).
'G℃'(:(si,giga(:(si,degree_Celsius)))).
'T℃'(:(si,tera(:(si,degree_Celsius)))).
'P℃'(:(si,peta(:(si,degree_Celsius)))).
'E℃'(:(si,exa(:(si,degree_Celsius)))).
'Z℃'(:(si,zetta(:(si,degree_Celsius)))).
'Y℃'(:(si,yotta(:(si,degree_Celsius)))).
'R℃'(:(si,ronna(:(si,degree_Celsius)))).
'Q℃'(:(si,quetta(:(si,degree_Celsius)))).
℃(:(si,degree_Celsius)).
degree_Celsius(:(si,degree_Celsius)).
qau(:(si,quecto(:(si,astronomical_unit)))).
rau(:(si,ronto(:(si,astronomical_unit)))).
yau(:(si,yocto(:(si,astronomical_unit)))).
zau(:(si,zepto(:(si,astronomical_unit)))).
aau(:(si,atto(:(si,astronomical_unit)))).
fau(:(si,femto(:(si,astronomical_unit)))).
pau(:(si,pico(:(si,astronomical_unit)))).
nau(:(si,nano(:(si,astronomical_unit)))).
µau(:(si,micro(:(si,astronomical_unit)))).
mau(:(si,milli(:(si,astronomical_unit)))).
cau(:(si,centi(:(si,astronomical_unit)))).
dau(:(si,deci(:(si,astronomical_unit)))).
daau(:(si,deca(:(si,astronomical_unit)))).
hau(:(si,hecto(:(si,astronomical_unit)))).
kau(:(si,kilo(:(si,astronomical_unit)))).
'Mau'(:(si,mega(:(si,astronomical_unit)))).
'Gau'(:(si,giga(:(si,astronomical_unit)))).
'Tau'(:(si,tera(:(si,astronomical_unit)))).
'Pau'(:(si,peta(:(si,astronomical_unit)))).
'Eau'(:(si,exa(:(si,astronomical_unit)))).
'Zau'(:(si,zetta(:(si,astronomical_unit)))).
'Yau'(:(si,yotta(:(si,astronomical_unit)))).
'Rau'(:(si,ronna(:(si,astronomical_unit)))).
'Qau'(:(si,quetta(:(si,astronomical_unit)))).
au(:(si,astronomical_unit)).
astronomical_unit(:(si,astronomical_unit)).
qd(:(si,quecto(:(si,day)))).
zd(:(si,zepto(:(si,day)))).
ad(:(si,atto(:(si,day)))).
fd(:(si,femto(:(si,day)))).
pd(:(si,pico(:(si,day)))).
nd(:(si,nano(:(si,day)))).
µd(:(si,micro(:(si,day)))).
md(:(si,milli(:(si,day)))).
dd(:(si,deci(:(si,day)))).
dad(:(si,deca(:(si,day)))).
hd(:(si,hecto(:(si,day)))).
kd(:(si,kilo(:(si,day)))).
'Md'(:(si,mega(:(si,day)))).
'Gd'(:(si,giga(:(si,day)))).
'Td'(:(si,tera(:(si,day)))).
'Pd'(:(si,peta(:(si,day)))).
'Ed'(:(si,exa(:(si,day)))).
'Zd'(:(si,zetta(:(si,day)))).
'Yd'(:(si,yotta(:(si,day)))).
'Rd'(:(si,ronna(:(si,day)))).
'Qd'(:(si,quetta(:(si,day)))).
d(:(si,day)).
day(:(si,day)).
qmin(:(si,quecto(:(si,minute)))).
rmin(:(si,ronto(:(si,minute)))).
ymin(:(si,yocto(:(si,minute)))).
zmin(:(si,zepto(:(si,minute)))).
amin(:(si,atto(:(si,minute)))).
fmin(:(si,femto(:(si,minute)))).
pmin(:(si,pico(:(si,minute)))).
nmin(:(si,nano(:(si,minute)))).
µmin(:(si,micro(:(si,minute)))).
mmin(:(si,milli(:(si,minute)))).
cmin(:(si,centi(:(si,minute)))).
dmin(:(si,deci(:(si,minute)))).
damin(:(si,deca(:(si,minute)))).
hmin(:(si,hecto(:(si,minute)))).
kmin(:(si,kilo(:(si,minute)))).
'Mmin'(:(si,mega(:(si,minute)))).
'Gmin'(:(si,giga(:(si,minute)))).
'Tmin'(:(si,tera(:(si,minute)))).
'Pmin'(:(si,peta(:(si,minute)))).
'Emin'(:(si,exa(:(si,minute)))).
'Zmin'(:(si,zetta(:(si,minute)))).
'Ymin'(:(si,yotta(:(si,minute)))).
'Rmin'(:(si,ronna(:(si,minute)))).
'Qmin'(:(si,quetta(:(si,minute)))).
min(:(si,minute)).
minute(:(si,minute)).
qPa(:(si,quecto(:(si,pascal)))).
rPa(:(si,ronto(:(si,pascal)))).
yPa(:(si,yocto(:(si,pascal)))).
zPa(:(si,zepto(:(si,pascal)))).
aPa(:(si,atto(:(si,pascal)))).
fPa(:(si,femto(:(si,pascal)))).
pPa(:(si,pico(:(si,pascal)))).
nPa(:(si,nano(:(si,pascal)))).
µPa(:(si,micro(:(si,pascal)))).
mPa(:(si,milli(:(si,pascal)))).
cPa(:(si,centi(:(si,pascal)))).
dPa(:(si,deci(:(si,pascal)))).
daPa(:(si,deca(:(si,pascal)))).
hPa(:(si,hecto(:(si,pascal)))).
kPa(:(si,kilo(:(si,pascal)))).
'MPa'(:(si,mega(:(si,pascal)))).
'GPa'(:(si,giga(:(si,pascal)))).
'TPa'(:(si,tera(:(si,pascal)))).
'PPa'(:(si,peta(:(si,pascal)))).
'EPa'(:(si,exa(:(si,pascal)))).
'ZPa'(:(si,zetta(:(si,pascal)))).
'YPa'(:(si,yotta(:(si,pascal)))).
'RPa'(:(si,ronna(:(si,pascal)))).
'QPa'(:(si,quetta(:(si,pascal)))).
'Pa'(:(si,pascal)).
pascal(:(si,pascal)).
qN(:(si,quecto(:(si,newton)))).
rN(:(si,ronto(:(si,newton)))).
yN(:(si,yocto(:(si,newton)))).
zN(:(si,zepto(:(si,newton)))).
aN(:(si,atto(:(si,newton)))).
fN(:(si,femto(:(si,newton)))).
pN(:(si,pico(:(si,newton)))).
nN(:(si,nano(:(si,newton)))).
µN(:(si,micro(:(si,newton)))).
mN(:(si,milli(:(si,newton)))).
cN(:(si,centi(:(si,newton)))).
dN(:(si,deci(:(si,newton)))).
daN(:(si,deca(:(si,newton)))).
hN(:(si,hecto(:(si,newton)))).
kN(:(si,kilo(:(si,newton)))).
'MN'(:(si,mega(:(si,newton)))).
'GN'(:(si,giga(:(si,newton)))).
'TN'(:(si,tera(:(si,newton)))).
'PN'(:(si,peta(:(si,newton)))).
'EN'(:(si,exa(:(si,newton)))).
'ZN'(:(si,zetta(:(si,newton)))).
'YN'(:(si,yotta(:(si,newton)))).
'RN'(:(si,ronna(:(si,newton)))).
'QN'(:(si,quetta(:(si,newton)))).
'N'(:(si,newton)).
newton(:(si,newton)).
qV(:(si,quecto(:(si,volt)))).
rV(:(si,ronto(:(si,volt)))).
yV(:(si,yocto(:(si,volt)))).
zV(:(si,zepto(:(si,volt)))).
aV(:(si,atto(:(si,volt)))).
fV(:(si,femto(:(si,volt)))).
pV(:(si,pico(:(si,volt)))).
nV(:(si,nano(:(si,volt)))).
µV(:(si,micro(:(si,volt)))).
mV(:(si,milli(:(si,volt)))).
cV(:(si,centi(:(si,volt)))).
dV(:(si,deci(:(si,volt)))).
daV(:(si,deca(:(si,volt)))).
hV(:(si,hecto(:(si,volt)))).
kV(:(si,kilo(:(si,volt)))).
'MV'(:(si,mega(:(si,volt)))).
'GV'(:(si,giga(:(si,volt)))).
'TV'(:(si,tera(:(si,volt)))).
'PV'(:(si,peta(:(si,volt)))).
'EV'(:(si,exa(:(si,volt)))).
'ZV'(:(si,zetta(:(si,volt)))).
'YV'(:(si,yotta(:(si,volt)))).
'RV'(:(si,ronna(:(si,volt)))).
'QV'(:(si,quetta(:(si,volt)))).
'V'(:(si,volt)).
volt(:(si,volt)).
qF(:(si,quecto(:(si,farad)))).
rF(:(si,ronto(:(si,farad)))).
yF(:(si,yocto(:(si,farad)))).
zF(:(si,zepto(:(si,farad)))).
aF(:(si,atto(:(si,farad)))).
fF(:(si,femto(:(si,farad)))).
pF(:(si,pico(:(si,farad)))).
nF(:(si,nano(:(si,farad)))).
µF(:(si,micro(:(si,farad)))).
mF(:(si,milli(:(si,farad)))).
cF(:(si,centi(:(si,farad)))).
dF(:(si,deci(:(si,farad)))).
daF(:(si,deca(:(si,farad)))).
hF(:(si,hecto(:(si,farad)))).
kF(:(si,kilo(:(si,farad)))).
'MF'(:(si,mega(:(si,farad)))).
'GF'(:(si,giga(:(si,farad)))).
'TF'(:(si,tera(:(si,farad)))).
'PF'(:(si,peta(:(si,farad)))).
'EF'(:(si,exa(:(si,farad)))).
'ZF'(:(si,zetta(:(si,farad)))).
'YF'(:(si,yotta(:(si,farad)))).
'RF'(:(si,ronna(:(si,farad)))).
'QF'(:(si,quetta(:(si,farad)))).
'F'(:(si,farad)).
farad(:(si,farad)).
qΩ(:(si,quecto(:(si,ohm)))).
rΩ(:(si,ronto(:(si,ohm)))).
yΩ(:(si,yocto(:(si,ohm)))).
zΩ(:(si,zepto(:(si,ohm)))).
aΩ(:(si,atto(:(si,ohm)))).
fΩ(:(si,femto(:(si,ohm)))).
pΩ(:(si,pico(:(si,ohm)))).
nΩ(:(si,nano(:(si,ohm)))).
µΩ(:(si,micro(:(si,ohm)))).
mΩ(:(si,milli(:(si,ohm)))).
cΩ(:(si,centi(:(si,ohm)))).
dΩ(:(si,deci(:(si,ohm)))).
daΩ(:(si,deca(:(si,ohm)))).
hΩ(:(si,hecto(:(si,ohm)))).
kΩ(:(si,kilo(:(si,ohm)))).
'MΩ'(:(si,mega(:(si,ohm)))).
'GΩ'(:(si,giga(:(si,ohm)))).
'TΩ'(:(si,tera(:(si,ohm)))).
'PΩ'(:(si,peta(:(si,ohm)))).
'EΩ'(:(si,exa(:(si,ohm)))).
'ZΩ'(:(si,zetta(:(si,ohm)))).
'YΩ'(:(si,yotta(:(si,ohm)))).
'RΩ'(:(si,ronna(:(si,ohm)))).
'QΩ'(:(si,quetta(:(si,ohm)))).
'Ω'(:(si,ohm)).
ohm(:(si,ohm)).
qe(:(si,quecto(:(si,elementary_charge)))).
re(:(si,ronto(:(si,elementary_charge)))).
ye(:(si,yocto(:(si,elementary_charge)))).
ze(:(si,zepto(:(si,elementary_charge)))).
ae(:(si,atto(:(si,elementary_charge)))).
fe(:(si,femto(:(si,elementary_charge)))).
pe(:(si,pico(:(si,elementary_charge)))).
ne(:(si,nano(:(si,elementary_charge)))).
µe(:(si,micro(:(si,elementary_charge)))).
me(:(si,milli(:(si,elementary_charge)))).
ce(:(si,centi(:(si,elementary_charge)))).
de(:(si,deci(:(si,elementary_charge)))).
dae(:(si,deca(:(si,elementary_charge)))).
he(:(si,hecto(:(si,elementary_charge)))).
ke(:(si,kilo(:(si,elementary_charge)))).
'Me'(:(si,mega(:(si,elementary_charge)))).
'Ge'(:(si,giga(:(si,elementary_charge)))).
'Te'(:(si,tera(:(si,elementary_charge)))).
'Pe'(:(si,peta(:(si,elementary_charge)))).
'Ee'(:(si,exa(:(si,elementary_charge)))).
'Ze'(:(si,zetta(:(si,elementary_charge)))).
'Ye'(:(si,yotta(:(si,elementary_charge)))).
'Re'(:(si,ronna(:(si,elementary_charge)))).
'Qe'(:(si,quetta(:(si,elementary_charge)))).
e(:(si,elementary_charge)).
elementary_charge(:(si,elementary_charge)).
qS(:(si,quecto(:(si,siemens)))).
rS(:(si,ronto(:(si,siemens)))).
yS(:(si,yocto(:(si,siemens)))).
zS(:(si,zepto(:(si,siemens)))).
aS(:(si,atto(:(si,siemens)))).
fS(:(si,femto(:(si,siemens)))).
pS(:(si,pico(:(si,siemens)))).
nS(:(si,nano(:(si,siemens)))).
µS(:(si,micro(:(si,siemens)))).
mS(:(si,milli(:(si,siemens)))).
cS(:(si,centi(:(si,siemens)))).
dS(:(si,deci(:(si,siemens)))).
daS(:(si,deca(:(si,siemens)))).
hS(:(si,hecto(:(si,siemens)))).
kS(:(si,kilo(:(si,siemens)))).
'MS'(:(si,mega(:(si,siemens)))).
'GS'(:(si,giga(:(si,siemens)))).
'TS'(:(si,tera(:(si,siemens)))).
'PS'(:(si,peta(:(si,siemens)))).
'ES'(:(si,exa(:(si,siemens)))).
'ZS'(:(si,zetta(:(si,siemens)))).
'YS'(:(si,yotta(:(si,siemens)))).
'RS'(:(si,ronna(:(si,siemens)))).
'QS'(:(si,quetta(:(si,siemens)))).
'S'(:(si,siemens)).
siemens(:(si,siemens)).
qWb(:(si,quecto(:(si,weber)))).
rWb(:(si,ronto(:(si,weber)))).
yWb(:(si,yocto(:(si,weber)))).
zWb(:(si,zepto(:(si,weber)))).
aWb(:(si,atto(:(si,weber)))).
fWb(:(si,femto(:(si,weber)))).
pWb(:(si,pico(:(si,weber)))).
nWb(:(si,nano(:(si,weber)))).
µWb(:(si,micro(:(si,weber)))).
mWb(:(si,milli(:(si,weber)))).
cWb(:(si,centi(:(si,weber)))).
dWb(:(si,deci(:(si,weber)))).
daWb(:(si,deca(:(si,weber)))).
hWb(:(si,hecto(:(si,weber)))).
kWb(:(si,kilo(:(si,weber)))).
'MWb'(:(si,mega(:(si,weber)))).
'GWb'(:(si,giga(:(si,weber)))).
'TWb'(:(si,tera(:(si,weber)))).
'PWb'(:(si,peta(:(si,weber)))).
'EWb'(:(si,exa(:(si,weber)))).
'ZWb'(:(si,zetta(:(si,weber)))).
'YWb'(:(si,yotta(:(si,weber)))).
'RWb'(:(si,ronna(:(si,weber)))).
'QWb'(:(si,quetta(:(si,weber)))).
'Wb'(:(si,weber)).
weber(:(si,weber)).
qT(:(si,quecto(:(si,tesla)))).
rT(:(si,ronto(:(si,tesla)))).
yT(:(si,yocto(:(si,tesla)))).
zT(:(si,zepto(:(si,tesla)))).
aT(:(si,atto(:(si,tesla)))).
fT(:(si,femto(:(si,tesla)))).
pT(:(si,pico(:(si,tesla)))).
nT(:(si,nano(:(si,tesla)))).
µT(:(si,micro(:(si,tesla)))).
mT(:(si,milli(:(si,tesla)))).
cT(:(si,centi(:(si,tesla)))).
dT(:(si,deci(:(si,tesla)))).
daT(:(si,deca(:(si,tesla)))).
hT(:(si,hecto(:(si,tesla)))).
kT(:(si,kilo(:(si,tesla)))).
'MT'(:(si,mega(:(si,tesla)))).
'GT'(:(si,giga(:(si,tesla)))).
'TT'(:(si,tera(:(si,tesla)))).
'PT'(:(si,peta(:(si,tesla)))).
'ET'(:(si,exa(:(si,tesla)))).
'ZT'(:(si,zetta(:(si,tesla)))).
'YT'(:(si,yotta(:(si,tesla)))).
'RT'(:(si,ronna(:(si,tesla)))).
'QT'(:(si,quetta(:(si,tesla)))).
'T'(:(si,tesla)).
tesla(:(si,tesla)).
qlx(:(si,quecto(:(si,lux)))).
rlx(:(si,ronto(:(si,lux)))).
ylx(:(si,yocto(:(si,lux)))).
zlx(:(si,zepto(:(si,lux)))).
alx(:(si,atto(:(si,lux)))).
flx(:(si,femto(:(si,lux)))).
plx(:(si,pico(:(si,lux)))).
nlx(:(si,nano(:(si,lux)))).
µlx(:(si,micro(:(si,lux)))).
mlx(:(si,milli(:(si,lux)))).
clx(:(si,centi(:(si,lux)))).
dlx(:(si,deci(:(si,lux)))).
dalx(:(si,deca(:(si,lux)))).
hlx(:(si,hecto(:(si,lux)))).
klx(:(si,kilo(:(si,lux)))).
'Mlx'(:(si,mega(:(si,lux)))).
'Glx'(:(si,giga(:(si,lux)))).
'Tlx'(:(si,tera(:(si,lux)))).
'Plx'(:(si,peta(:(si,lux)))).
'Elx'(:(si,exa(:(si,lux)))).
'Zlx'(:(si,zetta(:(si,lux)))).
'Ylx'(:(si,yotta(:(si,lux)))).
'Rlx'(:(si,ronna(:(si,lux)))).
'Qlx'(:(si,quetta(:(si,lux)))).
lx(:(si,lux)).
lux(:(si,lux)).
qkat(:(si,quecto(:(si,katal)))).
rkat(:(si,ronto(:(si,katal)))).
ykat(:(si,yocto(:(si,katal)))).
zkat(:(si,zepto(:(si,katal)))).
akat(:(si,atto(:(si,katal)))).
fkat(:(si,femto(:(si,katal)))).
pkat(:(si,pico(:(si,katal)))).
nkat(:(si,nano(:(si,katal)))).
µkat(:(si,micro(:(si,katal)))).
mkat(:(si,milli(:(si,katal)))).
ckat(:(si,centi(:(si,katal)))).
dkat(:(si,deci(:(si,katal)))).
dakat(:(si,deca(:(si,katal)))).
hkat(:(si,hecto(:(si,katal)))).
kkat(:(si,kilo(:(si,katal)))).
'Mkat'(:(si,mega(:(si,katal)))).
'Gkat'(:(si,giga(:(si,katal)))).
'Tkat'(:(si,tera(:(si,katal)))).
'Pkat'(:(si,peta(:(si,katal)))).
'Ekat'(:(si,exa(:(si,katal)))).
'Zkat'(:(si,zetta(:(si,katal)))).
'Ykat'(:(si,yotta(:(si,katal)))).
'Rkat'(:(si,ronna(:(si,katal)))).
'Qkat'(:(si,quetta(:(si,katal)))).
kat(:(si,katal)).
katal(:(si,katal)).
qHz(:(si,quecto(:(si,hertz)))).
rHz(:(si,ronto(:(si,hertz)))).
yHz(:(si,yocto(:(si,hertz)))).
zHz(:(si,zepto(:(si,hertz)))).
aHz(:(si,atto(:(si,hertz)))).
fHz(:(si,femto(:(si,hertz)))).
pHz(:(si,pico(:(si,hertz)))).
nHz(:(si,nano(:(si,hertz)))).
µHz(:(si,micro(:(si,hertz)))).
mHz(:(si,milli(:(si,hertz)))).
cHz(:(si,centi(:(si,hertz)))).
dHz(:(si,deci(:(si,hertz)))).
daHz(:(si,deca(:(si,hertz)))).
hHz(:(si,hecto(:(si,hertz)))).
kHz(:(si,kilo(:(si,hertz)))).
'MHz'(:(si,mega(:(si,hertz)))).
'GHz'(:(si,giga(:(si,hertz)))).
'THz'(:(si,tera(:(si,hertz)))).
'PHz'(:(si,peta(:(si,hertz)))).
'EHz'(:(si,exa(:(si,hertz)))).
'ZHz'(:(si,zetta(:(si,hertz)))).
'YHz'(:(si,yotta(:(si,hertz)))).
'RHz'(:(si,ronna(:(si,hertz)))).
'QHz'(:(si,quetta(:(si,hertz)))).
'Hz'(:(si,hertz)).
hertz(:(si,hertz)).
qℎ(:(si,quecto(:(si,planck_constant)))).
rℎ(:(si,ronto(:(si,planck_constant)))).
yℎ(:(si,yocto(:(si,planck_constant)))).
zℎ(:(si,zepto(:(si,planck_constant)))).
aℎ(:(si,atto(:(si,planck_constant)))).
fℎ(:(si,femto(:(si,planck_constant)))).
pℎ(:(si,pico(:(si,planck_constant)))).
nℎ(:(si,nano(:(si,planck_constant)))).
µℎ(:(si,micro(:(si,planck_constant)))).
mℎ(:(si,milli(:(si,planck_constant)))).
cℎ(:(si,centi(:(si,planck_constant)))).
dℎ(:(si,deci(:(si,planck_constant)))).
daℎ(:(si,deca(:(si,planck_constant)))).
hℎ(:(si,hecto(:(si,planck_constant)))).
kℎ(:(si,kilo(:(si,planck_constant)))).
'Mℎ'(:(si,mega(:(si,planck_constant)))).
'Gℎ'(:(si,giga(:(si,planck_constant)))).
'Tℎ'(:(si,tera(:(si,planck_constant)))).
'Pℎ'(:(si,peta(:(si,planck_constant)))).
'Eℎ'(:(si,exa(:(si,planck_constant)))).
'Zℎ'(:(si,zetta(:(si,planck_constant)))).
'Yℎ'(:(si,yotta(:(si,planck_constant)))).
'Rℎ'(:(si,ronna(:(si,planck_constant)))).
'Qℎ'(:(si,quetta(:(si,planck_constant)))).
ℎ(:(si,planck_constant)).
planck_constant(:(si,planck_constant)).
qW(:(si,quecto(:(si,watt)))).
rW(:(si,ronto(:(si,watt)))).
yW(:(si,yocto(:(si,watt)))).
zW(:(si,zepto(:(si,watt)))).
aW(:(si,atto(:(si,watt)))).
fW(:(si,femto(:(si,watt)))).
pW(:(si,pico(:(si,watt)))).
nW(:(si,nano(:(si,watt)))).
µW(:(si,micro(:(si,watt)))).
mW(:(si,milli(:(si,watt)))).
cW(:(si,centi(:(si,watt)))).
dW(:(si,deci(:(si,watt)))).
daW(:(si,deca(:(si,watt)))).
hW(:(si,hecto(:(si,watt)))).
kW(:(si,kilo(:(si,watt)))).
'MW'(:(si,mega(:(si,watt)))).
'GW'(:(si,giga(:(si,watt)))).
'TW'(:(si,tera(:(si,watt)))).
'PW'(:(si,peta(:(si,watt)))).
'EW'(:(si,exa(:(si,watt)))).
'ZW'(:(si,zetta(:(si,watt)))).
'YW'(:(si,yotta(:(si,watt)))).
'RW'(:(si,ronna(:(si,watt)))).
'QW'(:(si,quetta(:(si,watt)))).
'W'(:(si,watt)).
watt(:(si,watt)).
qh(:(si,quecto(:(si,hour)))).
rh(:(si,ronto(:(si,hour)))).
yh(:(si,yocto(:(si,hour)))).
zh(:(si,zepto(:(si,hour)))).
ah(:(si,atto(:(si,hour)))).
fh(:(si,femto(:(si,hour)))).
ph(:(si,pico(:(si,hour)))).
nh(:(si,nano(:(si,hour)))).
µh(:(si,micro(:(si,hour)))).
mh(:(si,milli(:(si,hour)))).
dh(:(si,deci(:(si,hour)))).
dah(:(si,deca(:(si,hour)))).
hh(:(si,hecto(:(si,hour)))).
kh(:(si,kilo(:(si,hour)))).
'Mh'(:(si,mega(:(si,hour)))).
'Gh'(:(si,giga(:(si,hour)))).
'Th'(:(si,tera(:(si,hour)))).
'Ph'(:(si,peta(:(si,hour)))).
'Eh'(:(si,exa(:(si,hour)))).
'Zh'(:(si,zetta(:(si,hour)))).
'Yh'(:(si,yotta(:(si,hour)))).
'Rh'(:(si,ronna(:(si,hour)))).
'Qh'(:(si,quetta(:(si,hour)))).
h(:(si,hour)).
hour(:(si,hour)).
qΔν_Cs(:(si,quecto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
rΔν_Cs(:(si,ronto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
yΔν_Cs(:(si,yocto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
zΔν_Cs(:(si,zepto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
aΔν_Cs(:(si,atto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
fΔν_Cs(:(si,femto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
pΔν_Cs(:(si,pico(:(si,hyperfine_structure_transition_frequency_of_cs)))).
nΔν_Cs(:(si,nano(:(si,hyperfine_structure_transition_frequency_of_cs)))).
µΔν_Cs(:(si,micro(:(si,hyperfine_structure_transition_frequency_of_cs)))).
mΔν_Cs(:(si,milli(:(si,hyperfine_structure_transition_frequency_of_cs)))).
cΔν_Cs(:(si,centi(:(si,hyperfine_structure_transition_frequency_of_cs)))).
dΔν_Cs(:(si,deci(:(si,hyperfine_structure_transition_frequency_of_cs)))).
daΔν_Cs(:(si,deca(:(si,hyperfine_structure_transition_frequency_of_cs)))).
hΔν_Cs(:(si,hecto(:(si,hyperfine_structure_transition_frequency_of_cs)))).
kΔν_Cs(:(si,kilo(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'MΔν_Cs'(:(si,mega(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'GΔν_Cs'(:(si,giga(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'TΔν_Cs'(:(si,tera(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'PΔν_Cs'(:(si,peta(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'EΔν_Cs'(:(si,exa(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'ZΔν_Cs'(:(si,zetta(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'YΔν_Cs'(:(si,yotta(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'RΔν_Cs'(:(si,ronna(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'QΔν_Cs'(:(si,quetta(:(si,hyperfine_structure_transition_frequency_of_cs)))).
'Δν_Cs'(:(si,hyperfine_structure_transition_frequency_of_cs)).
hyperfine_structure_transition_frequency_of_cs(:(si,hyperfine_structure_transition_frequency_of_cs)).
qg(:(si,quecto(:(si,gram)))).
rg(:(si,ronto(:(si,gram)))).
yg(:(si,yocto(:(si,gram)))).
zg(:(si,zepto(:(si,gram)))).
ag(:(si,atto(:(si,gram)))).
fg(:(si,femto(:(si,gram)))).
pg(:(si,pico(:(si,gram)))).
ng(:(si,nano(:(si,gram)))).
µg(:(si,micro(:(si,gram)))).
mg(:(si,milli(:(si,gram)))).
cg(:(si,centi(:(si,gram)))).
dg(:(si,deci(:(si,gram)))).
dag(:(si,deca(:(si,gram)))).
hg(:(si,hecto(:(si,gram)))).
kg(:(si,kilo(:(si,gram)))).
'Mg'(:(si,mega(:(si,gram)))).
'Gg'(:(si,giga(:(si,gram)))).
'Tg'(:(si,tera(:(si,gram)))).
'Pg'(:(si,peta(:(si,gram)))).
'Eg'(:(si,exa(:(si,gram)))).
'Zg'(:(si,zetta(:(si,gram)))).
'Yg'(:(si,yotta(:(si,gram)))).
'Rg'(:(si,ronna(:(si,gram)))).
'Qg'(:(si,quetta(:(si,gram)))).
g(:(si,gram)).
gram(:(si,gram)).
qN_A(:(si,quecto(:(si,avogadro_constant)))).
rN_A(:(si,ronto(:(si,avogadro_constant)))).
yN_A(:(si,yocto(:(si,avogadro_constant)))).
zN_A(:(si,zepto(:(si,avogadro_constant)))).
aN_A(:(si,atto(:(si,avogadro_constant)))).
fN_A(:(si,femto(:(si,avogadro_constant)))).
pN_A(:(si,pico(:(si,avogadro_constant)))).
nN_A(:(si,nano(:(si,avogadro_constant)))).
µN_A(:(si,micro(:(si,avogadro_constant)))).
mN_A(:(si,milli(:(si,avogadro_constant)))).
cN_A(:(si,centi(:(si,avogadro_constant)))).
dN_A(:(si,deci(:(si,avogadro_constant)))).
daN_A(:(si,deca(:(si,avogadro_constant)))).
hN_A(:(si,hecto(:(si,avogadro_constant)))).
kN_A(:(si,kilo(:(si,avogadro_constant)))).
'MN_A'(:(si,mega(:(si,avogadro_constant)))).
'GN_A'(:(si,giga(:(si,avogadro_constant)))).
'TN_A'(:(si,tera(:(si,avogadro_constant)))).
'PN_A'(:(si,peta(:(si,avogadro_constant)))).
'EN_A'(:(si,exa(:(si,avogadro_constant)))).
'ZN_A'(:(si,zetta(:(si,avogadro_constant)))).
'YN_A'(:(si,yotta(:(si,avogadro_constant)))).
'RN_A'(:(si,ronna(:(si,avogadro_constant)))).
'QN_A'(:(si,quetta(:(si,avogadro_constant)))).
'N_A'(:(si,avogadro_constant)).
avogadro_constant(:(si,avogadro_constant)).
qmol(:(si,quecto(:(si,mole)))).
rmol(:(si,ronto(:(si,mole)))).
ymol(:(si,yocto(:(si,mole)))).
zmol(:(si,zepto(:(si,mole)))).
amol(:(si,atto(:(si,mole)))).
fmol(:(si,femto(:(si,mole)))).
pmol(:(si,pico(:(si,mole)))).
nmol(:(si,nano(:(si,mole)))).
µmol(:(si,micro(:(si,mole)))).
mmol(:(si,milli(:(si,mole)))).
cmol(:(si,centi(:(si,mole)))).
dmol(:(si,deci(:(si,mole)))).
damol(:(si,deca(:(si,mole)))).
hmol(:(si,hecto(:(si,mole)))).
kmol(:(si,kilo(:(si,mole)))).
'Mmol'(:(si,mega(:(si,mole)))).
'Gmol'(:(si,giga(:(si,mole)))).
'Tmol'(:(si,tera(:(si,mole)))).
'Pmol'(:(si,peta(:(si,mole)))).
'Emol'(:(si,exa(:(si,mole)))).
'Zmol'(:(si,zetta(:(si,mole)))).
'Ymol'(:(si,yotta(:(si,mole)))).
'Rmol'(:(si,ronna(:(si,mole)))).
'Qmol'(:(si,quetta(:(si,mole)))).
mol(:(si,mole)).
mole(:(si,mole)).
qK_cd(:(si,quecto(:(si,luminous_efficacy)))).
rK_cd(:(si,ronto(:(si,luminous_efficacy)))).
yK_cd(:(si,yocto(:(si,luminous_efficacy)))).
zK_cd(:(si,zepto(:(si,luminous_efficacy)))).
aK_cd(:(si,atto(:(si,luminous_efficacy)))).
fK_cd(:(si,femto(:(si,luminous_efficacy)))).
pK_cd(:(si,pico(:(si,luminous_efficacy)))).
nK_cd(:(si,nano(:(si,luminous_efficacy)))).
µK_cd(:(si,micro(:(si,luminous_efficacy)))).
mK_cd(:(si,milli(:(si,luminous_efficacy)))).
cK_cd(:(si,centi(:(si,luminous_efficacy)))).
dK_cd(:(si,deci(:(si,luminous_efficacy)))).
daK_cd(:(si,deca(:(si,luminous_efficacy)))).
hK_cd(:(si,hecto(:(si,luminous_efficacy)))).
kK_cd(:(si,kilo(:(si,luminous_efficacy)))).
'MK_cd'(:(si,mega(:(si,luminous_efficacy)))).
'GK_cd'(:(si,giga(:(si,luminous_efficacy)))).
'TK_cd'(:(si,tera(:(si,luminous_efficacy)))).
'PK_cd'(:(si,peta(:(si,luminous_efficacy)))).
'EK_cd'(:(si,exa(:(si,luminous_efficacy)))).
'ZK_cd'(:(si,zetta(:(si,luminous_efficacy)))).
'YK_cd'(:(si,yotta(:(si,luminous_efficacy)))).
'RK_cd'(:(si,ronna(:(si,luminous_efficacy)))).
'QK_cd'(:(si,quetta(:(si,luminous_efficacy)))).
'K_cd'(:(si,luminous_efficacy)).
luminous_efficacy(:(si,luminous_efficacy)).
qC(:(si,quecto(:(si,coulomb)))).
rC(:(si,ronto(:(si,coulomb)))).
yC(:(si,yocto(:(si,coulomb)))).
zC(:(si,zepto(:(si,coulomb)))).
aC(:(si,atto(:(si,coulomb)))).
fC(:(si,femto(:(si,coulomb)))).
pC(:(si,pico(:(si,coulomb)))).
nC(:(si,nano(:(si,coulomb)))).
µC(:(si,micro(:(si,coulomb)))).
mC(:(si,milli(:(si,coulomb)))).
cC(:(si,centi(:(si,coulomb)))).
dC(:(si,deci(:(si,coulomb)))).
daC(:(si,deca(:(si,coulomb)))).
hC(:(si,hecto(:(si,coulomb)))).
kC(:(si,kilo(:(si,coulomb)))).
'MC'(:(si,mega(:(si,coulomb)))).
'GC'(:(si,giga(:(si,coulomb)))).
'TC'(:(si,tera(:(si,coulomb)))).
'PC'(:(si,peta(:(si,coulomb)))).
'EC'(:(si,exa(:(si,coulomb)))).
'ZC'(:(si,zetta(:(si,coulomb)))).
'YC'(:(si,yotta(:(si,coulomb)))).
'RC'(:(si,ronna(:(si,coulomb)))).
'QC'(:(si,quetta(:(si,coulomb)))).
'C'(:(si,coulomb)).
coulomb(:(si,coulomb)).
qk(:(si,quecto(:(si,boltzmann_constant)))).
rk(:(si,ronto(:(si,boltzmann_constant)))).
yk(:(si,yocto(:(si,boltzmann_constant)))).
zk(:(si,zepto(:(si,boltzmann_constant)))).
ak(:(si,atto(:(si,boltzmann_constant)))).
fk(:(si,femto(:(si,boltzmann_constant)))).
nk(:(si,nano(:(si,boltzmann_constant)))).
µk(:(si,micro(:(si,boltzmann_constant)))).
mk(:(si,milli(:(si,boltzmann_constant)))).
ck(:(si,centi(:(si,boltzmann_constant)))).
dk(:(si,deci(:(si,boltzmann_constant)))).
dak(:(si,deca(:(si,boltzmann_constant)))).
hk(:(si,hecto(:(si,boltzmann_constant)))).
kk(:(si,kilo(:(si,boltzmann_constant)))).
'Mk'(:(si,mega(:(si,boltzmann_constant)))).
'Gk'(:(si,giga(:(si,boltzmann_constant)))).
'Tk'(:(si,tera(:(si,boltzmann_constant)))).
'Pk'(:(si,peta(:(si,boltzmann_constant)))).
'Ek'(:(si,exa(:(si,boltzmann_constant)))).
'Zk'(:(si,zetta(:(si,boltzmann_constant)))).
'Yk'(:(si,yotta(:(si,boltzmann_constant)))).
'Rk'(:(si,ronna(:(si,boltzmann_constant)))).
'Qk'(:(si,quetta(:(si,boltzmann_constant)))).
k(:(si,boltzmann_constant)).
boltzmann_constant(:(si,boltzmann_constant)).
'qμ₀'(:(si,quecto(:(si,magnetic_constant)))).
'rμ₀'(:(si,ronto(:(si,magnetic_constant)))).
'yμ₀'(:(si,yocto(:(si,magnetic_constant)))).
'zμ₀'(:(si,zepto(:(si,magnetic_constant)))).
'aμ₀'(:(si,atto(:(si,magnetic_constant)))).
'fμ₀'(:(si,femto(:(si,magnetic_constant)))).
'pμ₀'(:(si,pico(:(si,magnetic_constant)))).
'nμ₀'(:(si,nano(:(si,magnetic_constant)))).
'µμ₀'(:(si,micro(:(si,magnetic_constant)))).
'mμ₀'(:(si,milli(:(si,magnetic_constant)))).
'cμ₀'(:(si,centi(:(si,magnetic_constant)))).
'dμ₀'(:(si,deci(:(si,magnetic_constant)))).
'daμ₀'(:(si,deca(:(si,magnetic_constant)))).
'hμ₀'(:(si,hecto(:(si,magnetic_constant)))).
'kμ₀'(:(si,kilo(:(si,magnetic_constant)))).
'Mμ₀'(:(si,mega(:(si,magnetic_constant)))).
'Gμ₀'(:(si,giga(:(si,magnetic_constant)))).
'Tμ₀'(:(si,tera(:(si,magnetic_constant)))).
'Pμ₀'(:(si,peta(:(si,magnetic_constant)))).
'Eμ₀'(:(si,exa(:(si,magnetic_constant)))).
'Zμ₀'(:(si,zetta(:(si,magnetic_constant)))).
'Yμ₀'(:(si,yotta(:(si,magnetic_constant)))).
'Rμ₀'(:(si,ronna(:(si,magnetic_constant)))).
'Qμ₀'(:(si,quetta(:(si,magnetic_constant)))).
'μ₀'(:(si,magnetic_constant)).
magnetic_constant(:(si,magnetic_constant)).
qc(:(si,quecto(:(si,speed_of_light_in_vacuum)))).
rc(:(si,ronto(:(si,speed_of_light_in_vacuum)))).
yc(:(si,yocto(:(si,speed_of_light_in_vacuum)))).
zc(:(si,zepto(:(si,speed_of_light_in_vacuum)))).
ac(:(si,atto(:(si,speed_of_light_in_vacuum)))).
fc(:(si,femto(:(si,speed_of_light_in_vacuum)))).
nc(:(si,nano(:(si,speed_of_light_in_vacuum)))).
µc(:(si,micro(:(si,speed_of_light_in_vacuum)))).
mc(:(si,milli(:(si,speed_of_light_in_vacuum)))).
cc(:(si,centi(:(si,speed_of_light_in_vacuum)))).
dc(:(si,deci(:(si,speed_of_light_in_vacuum)))).
dac(:(si,deca(:(si,speed_of_light_in_vacuum)))).
hc(:(si,hecto(:(si,speed_of_light_in_vacuum)))).
kc(:(si,kilo(:(si,speed_of_light_in_vacuum)))).
'Mc'(:(si,mega(:(si,speed_of_light_in_vacuum)))).
'Gc'(:(si,giga(:(si,speed_of_light_in_vacuum)))).
'Tc'(:(si,tera(:(si,speed_of_light_in_vacuum)))).
'Pc'(:(si,peta(:(si,speed_of_light_in_vacuum)))).
'Ec'(:(si,exa(:(si,speed_of_light_in_vacuum)))).
'Zc'(:(si,zetta(:(si,speed_of_light_in_vacuum)))).
'Yc'(:(si,yotta(:(si,speed_of_light_in_vacuum)))).
'Rc'(:(si,ronna(:(si,speed_of_light_in_vacuum)))).
'Qc'(:(si,quetta(:(si,speed_of_light_in_vacuum)))).
c(:(si,speed_of_light_in_vacuum)).
speed_of_light_in_vacuum(:(si,speed_of_light_in_vacuum)).
