:-module(si_units,[]).
units:absolute_point_origin(si:absolute_zero,isq:thermodynamic_temperature).
units:alias(si:kilogram,si:kilo(si:gram)).
units:alias(si:zeroth_kelvin,si:absolute_zero).
units:alias(si:zeroth_degree_Celsius,si:ice_point).
units:alias(non_si:hectare,si:hecto(non_si:are)).
units:alias(si:electronvolt,non_si:electronvolt).
units:alias(si:dalton,non_si:dalton).
units:alias(si:tonne,non_si:tonne).
units:alias(si:litre,non_si:litre).
units:alias(si:hectare,non_si:hectare).
units:alias(si:are,non_si:are).
units:alias(si:arcsecond,non_si:arcsecond).
units:alias(si:arcminute,non_si:arcminute).
units:alias(si:degree,non_si:degree).
units:alias(si:astronomical_unit,non_si:astronomical_unit).
units:alias(si:day,non_si:day).
units:alias(si:hour,non_si:hour).
units:alias(si:minute,non_si:minute).
units:no_space_before_unit_symbol(non_si:degree).
units:no_space_before_unit_symbol(non_si:arcminute).
units:no_space_before_unit_symbol(non_si:arcsecond).
units:relative_point_origin(si:ice_point,273150*(si:milli(si:kelvin))).
units:unit_kind(si:second,isq:time).
units:unit_kind(si:metre,isq:length).
units:unit_kind(si:gram,isq:mass).
units:unit_kind(si:ampere,isq:electric_current).
units:unit_kind(si:kelvin,isq:thermodynamic_temperature).
units:unit_kind(si:mole,isq:amount_of_substance).
units:unit_kind(si:candela,isq:luminous_intensity).
units:unit_kind(si:radian,isq:angular_measure).
units:unit_kind(si:steradian,isq:solid_angular_measure).
units:unit_kind(si:hertz,isq:frequency).
units:unit_kind(si:becquerel,isq:activity).
units:unit_kind(si:gray,isq:absorbed_dose).
units:unit_kind(si:sievert,isq:dose_equivalent).
units:unit_symbol(si:second,s).
units:unit_symbol(si:metre,m).
units:unit_symbol(si:gram,g).
units:unit_symbol(si:ampere,'A').
units:unit_symbol(si:kelvin,'K').
units:unit_symbol(si:mole,mol).
units:unit_symbol(si:candela,cd).
units:unit_symbol_formula(si:radian,rad,(si:metre)/(si:metre)).
units:unit_symbol_formula(si:steradian,sr,(si:metre)**2/(si:metre)**2).
units:unit_symbol_formula(si:hertz,'Hz',1/(si:second)).
units:unit_symbol_formula(si:newton,'N',(si:kilogram)*(si:metre)/(si:second)**2).
units:unit_symbol_formula(si:pascal,'Pa',(si:newton)/(si:metre)**2).
units:unit_symbol_formula(si:joule,'J',(si:newton)*(si:metre)).
units:unit_symbol_formula(si:watt,'W',(si:joule)/(si:second)).
units:unit_symbol_formula(si:coulomb,'C',(si:ampere)*(si:second)).
units:unit_symbol_formula(si:volt,'V',(si:watt)/(si:ampere)).
units:unit_symbol_formula(si:farad,'F',(si:coulomb)/(si:volt)).
units:unit_symbol_formula(si:ohm,'Ω',(si:volt)/(si:ampere)).
units:unit_symbol_formula(si:siemens,'S',1/(si:ohm)).
units:unit_symbol_formula(si:weber,'Wb',(si:volt)*(si:second)).
units:unit_symbol_formula(si:tesla,'T',(si:weber)/(si:metre)**2).
units:unit_symbol_formula(si:henry,'H',(si:weber)/(si:ampere)).
units:unit_symbol_formula(si:degree_Celsius,℃,si:kelvin).
units:unit_symbol_formula(si:lumen,lm,(si:candela)*(si:steradian)).
units:unit_symbol_formula(si:lux,lx,(si:lumen)/(si:metre)**2).
units:unit_symbol_formula(si:becquerel,'Bq',1/(si:second)).
units:unit_symbol_formula(si:gray,'Gy',(si:joule)/(si:kilogram)).
units:unit_symbol_formula(si:sievert,'Sv',(si:joule)/(si:kilogram)).
units:unit_symbol_formula(si:katal,kat,(si:mole)/(si:second)).
units:unit_symbol_formula(non_si:minute,min,60*(si:second)).
units:unit_symbol_formula(non_si:hour,h,60*(non_si:minute)).
units:unit_symbol_formula(non_si:day,d,24*(non_si:hour)).
units:unit_symbol_formula(non_si:astronomical_unit,au,149597870700*(si:metre)).
units:unit_symbol_formula(non_si:degree,°,pi/180*(si:radian)).
units:unit_symbol_formula(non_si:arcminute,′,1/60*(non_si:degree)).
units:unit_symbol_formula(non_si:arcsecond,″,1/60*(non_si:arcminute)).
units:unit_symbol_formula(non_si:are,a,(si:deca(si:metre))**2).
units:unit_symbol_formula(non_si:litre,'L',(si:deci(si:metre))**3).
units:unit_symbol_formula(non_si:tonne,t,1000*(si:kilogram)).
units:unit_symbol_formula(non_si:dalton,'Da',16605390666050/10000000000000*10** -27*(si:kilogram)).
units:unit_symbol_formula(non_si:electronvolt,eV,1602176634/1000000000*10** -19*(si:joule)).
