:-module(imperial_symbol,[acre/1,rood/1,fur/1,furlong/1,'hp(I)'/1,mechanical_horsepower/1,psi/1,kn/1,knot/1,'Bc'/1,barleycorn/1,(in)/1,inch/1,th/1,thou/1,'fl oz'/1,fluid_ounce/1,lb/1,pound/1,oz/1,ounce/1,t/1,ton/1,p/1,(point)/1,hh/1,hand/1,pt/1,pint/1,qt/1,quart/1,gal/1,gallon/1,ftm/1,fathom/1,mi/1,mile/1,gi/1,gill/1,rd/1,rod/1,st/1,stone/1,cb/1,cable/1,perch/1,li/1,link/1,qr/1,quarter/1,mil/1,'P'/1,pica/1,ch/1,chain/1,lbf/1,pound_force/1,ft/1,foot/1,yd/1,yard/1,gr/1,grain/1,pdl/1,poundal/1,cwt/1,long_hundredweight/1,twip/1,nmi/1,nautical_mile/1,le/1,league/1]).
acre(:(imperial,acre)).
rood(:(imperial,rood)).
fur(:(imperial,furlong)).
furlong(:(imperial,furlong)).
'hp(I)'(:(imperial,mechanical_horsepower)).
mechanical_horsepower(:(imperial,mechanical_horsepower)).
psi(:(imperial,psi)).
kn(:(imperial,knot)).
knot(:(imperial,knot)).
'Bc'(:(imperial,barleycorn)).
barleycorn(:(imperial,barleycorn)).
in(:(imperial,inch)).
inch(:(imperial,inch)).
th(:(imperial,thou)).
thou(:(imperial,thou)).
'fl oz'(:(imperial,fluid_ounce)).
fluid_ounce(:(imperial,fluid_ounce)).
lb(:(imperial,pound)).
pound(:(imperial,pound)).
oz(:(imperial,ounce)).
ounce(:(imperial,ounce)).
t(:(imperial,ton)).
ton(:(imperial,ton)).
p(:(imperial,point)).
point(:(imperial,point)).
hh(:(imperial,hand)).
hand(:(imperial,hand)).
pt(:(imperial,pint)).
pint(:(imperial,pint)).
qt(:(imperial,quart)).
quart(:(imperial,quart)).
gal(:(imperial,gallon)).
gallon(:(imperial,gallon)).
ftm(:(imperial,fathom)).
fathom(:(imperial,fathom)).
mi(:(imperial,mile)).
mile(:(imperial,mile)).
gi(:(imperial,gill)).
gill(:(imperial,gill)).
rd(:(imperial,rod)).
rod(:(imperial,rod)).
st(:(imperial,stone)).
stone(:(imperial,stone)).
cb(:(imperial,cable)).
cable(:(imperial,cable)).
perch(:(imperial,perch)).
li(:(imperial,link)).
link(:(imperial,link)).
qr(:(imperial,quarter)).
quarter(:(imperial,quarter)).
mil(:(imperial,mil)).
'P'(:(imperial,pica)).
pica(:(imperial,pica)).
ch(:(imperial,chain)).
chain(:(imperial,chain)).
lbf(:(imperial,pound_force)).
pound_force(:(imperial,pound_force)).
ft(:(imperial,foot)).
foot(:(imperial,foot)).
yd(:(imperial,yard)).
yard(:(imperial,yard)).
gr(:(imperial,grain)).
grain(:(imperial,grain)).
pdl(:(imperial,poundal)).
poundal(:(imperial,poundal)).
cwt(:(imperial,long_hundredweight)).
long_hundredweight(:(imperial,long_hundredweight)).
twip(:(imperial,twip)).
nmi(:(imperial,nautical_mile)).
nautical_mile(:(imperial,nautical_mile)).
le(:(imperial,league)).
league(:(imperial,league)).
