:-module(non_si_symbol,[a/1,are/1,'Da'/1,dalton/1,eV/1,electronvolt/1,'L'/1,litre/1,t/1,tonne/1,′ / 1,arcminute/1,″ / 1,arcsecond/1,au/1,astronomical_unit/1,° / 1,degree/1,min/1,minute/1,d/1,day/1,h/1,hour/1]).
a(:(non_si,are)).
are(:(non_si,are)).
'Da'(:(non_si,dalton)).
dalton(:(non_si,dalton)).
eV(:(non_si,electronvolt)).
electronvolt(:(non_si,electronvolt)).
'L'(:(non_si,litre)).
litre(:(non_si,litre)).
t(:(non_si,tonne)).
tonne(:(non_si,tonne)).
′(:(non_si,arcminute)).
arcminute(:(non_si,arcminute)).
″(:(non_si,arcsecond)).
arcsecond(:(non_si,arcsecond)).
au(:(non_si,astronomical_unit)).
astronomical_unit(:(non_si,astronomical_unit)).
°(:(non_si,degree)).
degree(:(non_si,degree)).
min(:(non_si,minute)).
minute(:(non_si,minute)).
d(:(non_si,day)).
day(:(non_si,day)).
h(:(non_si,hour)).
hour(:(non_si,hour)).
