:-module(iau_symbol,['M_☉'/1,solar_mass/1,'M_EARTH'/1,'Earth_mass'/1,'Å'/1,angstrom/1,au/1,astronomical_unit/1,k/1,gaussian_gravitational_constant/1,pc/1,parsec/1,'H₀'/1,hubble_constant/1,'LD'/1,lunar_distance/1,'c₀'/1,speed_of_light/1,ly/1,light_year/1,'M_JUP'/1,'Jupiter_mass'/1,'D'/1,day/1,'G'/1,constant_of_gravitation/1,aj/1,'Julian_year'/1]).
'M_☉'(:(iau,solar_mass)).
solar_mass(:(iau,solar_mass)).
'M_EARTH'(:(iau,'Earth_mass')).
'Earth_mass'(:(iau,'Earth_mass')).
'Å'(:(iau,angstrom)).
angstrom(:(iau,angstrom)).
au(:(iau,astronomical_unit)).
astronomical_unit(:(iau,astronomical_unit)).
k(:(iau,gaussian_gravitational_constant)).
gaussian_gravitational_constant(:(iau,gaussian_gravitational_constant)).
pc(:(iau,parsec)).
parsec(:(iau,parsec)).
'H₀'(:(iau,hubble_constant)).
hubble_constant(:(iau,hubble_constant)).
'LD'(:(iau,lunar_distance)).
lunar_distance(:(iau,lunar_distance)).
'c₀'(:(iau,speed_of_light)).
speed_of_light(:(iau,speed_of_light)).
ly(:(iau,light_year)).
light_year(:(iau,light_year)).
'M_JUP'(:(iau,'Jupiter_mass')).
'Jupiter_mass'(:(iau,'Jupiter_mass')).
'D'(:(iau,day)).
day(:(iau,day)).
'G'(:(iau,constant_of_gravitation)).
constant_of_gravitation(:(iau,constant_of_gravitation)).
aj(:(iau,'Julian_year')).
'Julian_year'(:(iau,'Julian_year')).
