:-module(international_symbol,[(in)/1,inch/1,'hp(I)'/1,mechanical_horsepower/1,p/1,(point)/1,oz/1,ounce/1,lb/1,pound/1,gr/1,grain/1,dr/1,dram/1,'P'/1,pica/1,yd/1,yard/1,twip/1,mil/1,le/1,league/1,mi/1,mile/1,kn/1,knot/1,nmi/1,nautical_mile/1,pdl/1,poundal/1,psi/1,lbf/1,pound_force/1,ft/1,foot/1]).
in(:(international,inch)).
inch(:(international,inch)).
'hp(I)'(:(international,mechanical_horsepower)).
mechanical_horsepower(:(international,mechanical_horsepower)).
p(:(international,point)).
point(:(international,point)).
oz(:(international,ounce)).
ounce(:(international,ounce)).
lb(:(international,pound)).
pound(:(international,pound)).
gr(:(international,grain)).
grain(:(international,grain)).
dr(:(international,dram)).
dram(:(international,dram)).
'P'(:(international,pica)).
pica(:(international,pica)).
yd(:(international,yard)).
yard(:(international,yard)).
twip(:(international,twip)).
mil(:(international,mil)).
le(:(international,league)).
league(:(international,league)).
mi(:(international,mile)).
mile(:(international,mile)).
kn(:(international,knot)).
knot(:(international,knot)).
nmi(:(international,nautical_mile)).
nautical_mile(:(international,nautical_mile)).
pdl(:(international,poundal)).
poundal(:(international,poundal)).
psi(:(international,psi)).
lbf(:(international,pound_force)).
pound_force(:(international,pound_force)).
ft(:(international,foot)).
foot(:(international,foot)).
