:-module(international_symbol,[hp/1,mechanical_horsepower/1,psi/1,kn/1,knot/1,p/1,(point)/1,(in)/1,inch/1,'P'/1,pica/1,mil/1,gr/1,grain/1,yd/1,yard/1,pdl/1,poundal/1,le/1,league/1,nmi/1,nautical_mile/1,twip/1,mi/1,mile/1,dr/1,dram/1,lbf/1,pound_force/1,oz/1,ounce/1,ft/1,foot/1,lb/1,pound/1]).
hp(:(international,mechanical_horsepower)).
mechanical_horsepower(:(international,mechanical_horsepower)).
psi(:(international,psi)).
kn(:(international,knot)).
knot(:(international,knot)).
p(:(international,point)).
point(:(international,point)).
in(:(international,inch)).
inch(:(international,inch)).
'P'(:(international,pica)).
pica(:(international,pica)).
mil(:(international,mil)).
gr(:(international,grain)).
grain(:(international,grain)).
yd(:(international,yard)).
yard(:(international,yard)).
pdl(:(international,poundal)).
poundal(:(international,poundal)).
le(:(international,league)).
league(:(international,league)).
nmi(:(international,nautical_mile)).
nautical_mile(:(international,nautical_mile)).
twip(:(international,twip)).
mi(:(international,mile)).
mile(:(international,mile)).
dr(:(international,dram)).
dram(:(international,dram)).
lbf(:(international,pound_force)).
pound_force(:(international,pound_force)).
oz(:(international,ounce)).
ounce(:(international,ounce)).
ft(:(international,foot)).
foot(:(international,foot)).
lb(:(international,pound)).
pound(:(international,pound)).
