:-module(iec_symbol,['Kio'/1,'Mio'/1,'Gio'/1,'Tio'/1,'Pio'/1,'Eio'/1,'Zio'/1,'Yio'/1,o/1,octet/1,'KiB'/1,'MiB'/1,'GiB'/1,'TiB'/1,'PiB'/1,'EiB'/1,'ZiB'/1,'YiB'/1,'B'/1,byte/1,'Kibit'/1,'Mibit'/1,'Gibit'/1,'Tibit'/1,'Pibit'/1,'Eibit'/1,'Zibit'/1,'Yibit'/1,bit/1,'KiBd'/1,'MiBd'/1,'GiBd'/1,'TiBd'/1,'PiBd'/1,'EiBd'/1,'ZiBd'/1,'YiBd'/1,'Bd'/1,baud/1,'KiE'/1,'MiE'/1,'GiE'/1,'TiE'/1,'PiE'/1,'EiE'/1,'ZiE'/1,'YiE'/1,'E'/1,erlang/1,'Kivar'/1,'Mivar'/1,'Givar'/1,'Tivar'/1,'Pivar'/1,'Eivar'/1,'Zivar'/1,'Yivar'/1,var/1,volt_ampere_reactive_power/1]).
'Kio'(:(iec,kibi(:(iec,octet)))).
'Mio'(:(iec,mebi(:(iec,octet)))).
'Gio'(:(iec,gibi(:(iec,octet)))).
'Tio'(:(iec,tebi(:(iec,octet)))).
'Pio'(:(iec,pebi(:(iec,octet)))).
'Eio'(:(iec,exbi(:(iec,octet)))).
'Zio'(:(iec,zebi(:(iec,octet)))).
'Yio'(:(iec,yobi(:(iec,octet)))).
o(:(iec,octet)).
octet(:(iec,octet)).
'KiB'(:(iec,kibi(:(iec,byte)))).
'MiB'(:(iec,mebi(:(iec,byte)))).
'GiB'(:(iec,gibi(:(iec,byte)))).
'TiB'(:(iec,tebi(:(iec,byte)))).
'PiB'(:(iec,pebi(:(iec,byte)))).
'EiB'(:(iec,exbi(:(iec,byte)))).
'ZiB'(:(iec,zebi(:(iec,byte)))).
'YiB'(:(iec,yobi(:(iec,byte)))).
'B'(:(iec,byte)).
byte(:(iec,byte)).
'Kibit'(:(iec,kibi(:(iec,bit)))).
'Mibit'(:(iec,mebi(:(iec,bit)))).
'Gibit'(:(iec,gibi(:(iec,bit)))).
'Tibit'(:(iec,tebi(:(iec,bit)))).
'Pibit'(:(iec,pebi(:(iec,bit)))).
'Eibit'(:(iec,exbi(:(iec,bit)))).
'Zibit'(:(iec,zebi(:(iec,bit)))).
'Yibit'(:(iec,yobi(:(iec,bit)))).
bit(:(iec,bit)).
'KiBd'(:(iec,kibi(:(iec,baud)))).
'MiBd'(:(iec,mebi(:(iec,baud)))).
'GiBd'(:(iec,gibi(:(iec,baud)))).
'TiBd'(:(iec,tebi(:(iec,baud)))).
'PiBd'(:(iec,pebi(:(iec,baud)))).
'EiBd'(:(iec,exbi(:(iec,baud)))).
'ZiBd'(:(iec,zebi(:(iec,baud)))).
'YiBd'(:(iec,yobi(:(iec,baud)))).
'Bd'(:(iec,baud)).
baud(:(iec,baud)).
'KiE'(:(iec,kibi(:(iec,erlang)))).
'MiE'(:(iec,mebi(:(iec,erlang)))).
'GiE'(:(iec,gibi(:(iec,erlang)))).
'TiE'(:(iec,tebi(:(iec,erlang)))).
'PiE'(:(iec,pebi(:(iec,erlang)))).
'EiE'(:(iec,exbi(:(iec,erlang)))).
'ZiE'(:(iec,zebi(:(iec,erlang)))).
'YiE'(:(iec,yobi(:(iec,erlang)))).
'E'(:(iec,erlang)).
erlang(:(iec,erlang)).
'Kivar'(:(iec,kibi(:(iec,volt_ampere_reactive_power)))).
'Mivar'(:(iec,mebi(:(iec,volt_ampere_reactive_power)))).
'Givar'(:(iec,gibi(:(iec,volt_ampere_reactive_power)))).
'Tivar'(:(iec,tebi(:(iec,volt_ampere_reactive_power)))).
'Pivar'(:(iec,pebi(:(iec,volt_ampere_reactive_power)))).
'Eivar'(:(iec,exbi(:(iec,volt_ampere_reactive_power)))).
'Zivar'(:(iec,zebi(:(iec,volt_ampere_reactive_power)))).
'Yivar'(:(iec,yobi(:(iec,volt_ampere_reactive_power)))).
var(:(iec,volt_ampere_reactive_power)).
volt_ampere_reactive_power(:(iec,volt_ampere_reactive_power)).
