:-module(usc_symbol,[qt/1,quart/1,min/1,minim/1,pt/1,pint/1,'fl dr'/1,fluid_dram/1,gi/1,gill/1,oil_bbl/1,oil_barrel/1,'fl oz'/1,fluid_ounce/1,tbsp/1,tablespoon/1,li/1,link/1,c/1,cup/1,rd/1,rod/1,pot/1,pottle/1,tsp/1,teaspoon/1,gal/1,gallon/1,acre/1,jig/1,shot/1,bbl/1,barrel/1,hogshead/1,cwt/1,short_hundredweight/1,dwt/1,pennyweight/1,'oz t'/1,troy_once/1,'lb t'/1,troy_pound/1,inHg/1,inch_of_mercury/1,pk/1,peck/1,'hp(I)'/1,mechanical_horsepower/1,bu/1,bushel/1,dry_bbl/1,dry_barrel/1,dry_pt/1,dry_pint/1,dry_qt/1,dry_quart/1,dry_gal/1,dry_gallon/1,qr/1,quarter/1,p/1,(point)/1,(in)/1,inch/1,gr/1,grain/1,dr/1,dram/1,'P'/1,pica/1,yd/1,yard/1,twip/1,mil/1,le/1,league/1,mi/1,mile/1,kn/1,knot/1,nmi/1,nautical_mile/1,oz/1,ounce/1,pdl/1,poundal/1,lb/1,pound/1,psi/1,'ftm(us)'/1,fathom/1,'cb(us)'/1,cable/1,'°R'/1,rankine/1,fur/1,furlong/1,℉ / 1,degree_Fahrenheit/1,ch/1,chain/1,section/1,lbf/1,pound_force/1,ft/1,foot/1,t/1,ton/1]).
qt(:(usc,quart)).
quart(:(usc,quart)).
min(:(usc,minim)).
minim(:(usc,minim)).
pt(:(usc,pint)).
pint(:(usc,pint)).
'fl dr'(:(usc,fluid_dram)).
fluid_dram(:(usc,fluid_dram)).
gi(:(usc,gill)).
gill(:(usc,gill)).
oil_bbl(:(usc,oil_barrel)).
oil_barrel(:(usc,oil_barrel)).
'fl oz'(:(usc,fluid_ounce)).
fluid_ounce(:(usc,fluid_ounce)).
tbsp(:(usc,tablespoon)).
tablespoon(:(usc,tablespoon)).
li(:(usc,link)).
link(:(usc,link)).
c(:(usc,cup)).
cup(:(usc,cup)).
rd(:(usc,rod)).
rod(:(usc,rod)).
pot(:(usc,pottle)).
pottle(:(usc,pottle)).
tsp(:(usc,teaspoon)).
teaspoon(:(usc,teaspoon)).
gal(:(usc,gallon)).
gallon(:(usc,gallon)).
acre(:(usc,acre)).
jig(:(usc,shot)).
shot(:(usc,shot)).
bbl(:(usc,barrel)).
barrel(:(usc,barrel)).
hogshead(:(usc,hogshead)).
cwt(:(usc,short_hundredweight)).
short_hundredweight(:(usc,short_hundredweight)).
dwt(:(usc,pennyweight)).
pennyweight(:(usc,pennyweight)).
'oz t'(:(usc,troy_once)).
troy_once(:(usc,troy_once)).
'lb t'(:(usc,troy_pound)).
troy_pound(:(usc,troy_pound)).
inHg(:(usc,inch_of_mercury)).
inch_of_mercury(:(usc,inch_of_mercury)).
pk(:(usc,peck)).
peck(:(usc,peck)).
'hp(I)'(:(usc,mechanical_horsepower)).
mechanical_horsepower(:(usc,mechanical_horsepower)).
bu(:(usc,bushel)).
bushel(:(usc,bushel)).
dry_bbl(:(usc,dry_barrel)).
dry_barrel(:(usc,dry_barrel)).
dry_pt(:(usc,dry_pint)).
dry_pint(:(usc,dry_pint)).
dry_qt(:(usc,dry_quart)).
dry_quart(:(usc,dry_quart)).
dry_gal(:(usc,dry_gallon)).
dry_gallon(:(usc,dry_gallon)).
qr(:(usc,quarter)).
quarter(:(usc,quarter)).
p(:(usc,point)).
point(:(usc,point)).
in(:(usc,inch)).
inch(:(usc,inch)).
gr(:(usc,grain)).
grain(:(usc,grain)).
dr(:(usc,dram)).
dram(:(usc,dram)).
'P'(:(usc,pica)).
pica(:(usc,pica)).
yd(:(usc,yard)).
yard(:(usc,yard)).
twip(:(usc,twip)).
mil(:(usc,mil)).
le(:(usc,league)).
league(:(usc,league)).
mi(:(usc,mile)).
mile(:(usc,mile)).
kn(:(usc,knot)).
knot(:(usc,knot)).
nmi(:(usc,nautical_mile)).
nautical_mile(:(usc,nautical_mile)).
oz(:(usc,ounce)).
ounce(:(usc,ounce)).
pdl(:(usc,poundal)).
poundal(:(usc,poundal)).
lb(:(usc,pound)).
pound(:(usc,pound)).
psi(:(usc,psi)).
'ftm(us)'(:(usc,fathom)).
fathom(:(usc,fathom)).
'cb(us)'(:(usc,cable)).
cable(:(usc,cable)).
'°R'(:(usc,rankine)).
rankine(:(usc,rankine)).
fur(:(usc,furlong)).
furlong(:(usc,furlong)).
℉(:(usc,degree_Fahrenheit)).
degree_Fahrenheit(:(usc,degree_Fahrenheit)).
ch(:(usc,chain)).
chain(:(usc,chain)).
section(:(usc,section)).
lbf(:(usc,pound_force)).
pound_force(:(usc,pound_force)).
ft(:(usc,foot)).
foot(:(usc,foot)).
t(:(usc,ton)).
ton(:(usc,ton)).
