:-module(usc_symbol,['fl oz'/1,fluid_ounce/1,lb/1,pound/1,oz/1,ounce/1,pt/1,pint/1,gal/1,gallon/1,'ftm(us)'/1,fathom/1,mi/1,mile/1,gi/1,gill/1,rd/1,rod/1,tbsp/1,tablespoon/1,c/1,cup/1,'cb(us)'/1,cable/1,'°R'/1,rankine/1,qr/1,quarter/1,℉ / 1,degree_Fahrenheit/1,mil/1,dry_qt/1,dry_quart/1,ch/1,chain/1,dry_gal/1,dry_gallon/1,yd/1,yard/1,pk/1,peck/1,gr/1,grain/1,bu/1,bushel/1,pdl/1,poundal/1,dry_bbl/1,dry_barrel/1,hogshead/1,twip/1,bbl/1,barrel/1,min/1,minim/1,'fl dr'/1,fluid_dram/1,inHg/1,inch_of_mercury/1,tsp/1,teaspoon/1,'lb t'/1,troy_pound/1,psi/1,'oz t'/1,troy_once/1,kn/1,knot/1,cwt/1,short_hundredweight/1,dry_pt/1,dry_pint/1,ft/1,foot/1,acre/1,(in)/1,inch/1,t/1,ton/1,p/1,(point)/1,qt/1,quart/1,pot/1,pottle/1,section/1,li/1,link/1,'P'/1,pica/1,oil_bbl/1,oil_barrel/1,nmi/1,nautical_mile/1,le/1,league/1,fur/1,furlong/1,hp/1,mechanical_horsepower/1,jig/1,shot/1,dwt/1,pennyweight/1,lbf/1,pound_force/1,dr/1,dram/1,deg_F/1]).
'fl oz'(:(usc,fluid_ounce)).
fluid_ounce(:(usc,fluid_ounce)).
lb(:(usc,pound)).
pound(:(usc,pound)).
oz(:(usc,ounce)).
ounce(:(usc,ounce)).
pt(:(usc,pint)).
pint(:(usc,pint)).
gal(:(usc,gallon)).
gallon(:(usc,gallon)).
'ftm(us)'(:(usc,fathom)).
fathom(:(usc,fathom)).
mi(:(usc,mile)).
mile(:(usc,mile)).
gi(:(usc,gill)).
gill(:(usc,gill)).
rd(:(usc,rod)).
rod(:(usc,rod)).
tbsp(:(usc,tablespoon)).
tablespoon(:(usc,tablespoon)).
c(:(usc,cup)).
cup(:(usc,cup)).
'cb(us)'(:(usc,cable)).
cable(:(usc,cable)).
'°R'(:(usc,rankine)).
rankine(:(usc,rankine)).
qr(:(usc,quarter)).
quarter(:(usc,quarter)).
℉(:(usc,degree_Fahrenheit)).
degree_Fahrenheit(:(usc,degree_Fahrenheit)).
mil(:(usc,mil)).
dry_qt(:(usc,dry_quart)).
dry_quart(:(usc,dry_quart)).
ch(:(usc,chain)).
chain(:(usc,chain)).
dry_gal(:(usc,dry_gallon)).
dry_gallon(:(usc,dry_gallon)).
yd(:(usc,yard)).
yard(:(usc,yard)).
pk(:(usc,peck)).
peck(:(usc,peck)).
gr(:(usc,grain)).
grain(:(usc,grain)).
bu(:(usc,bushel)).
bushel(:(usc,bushel)).
pdl(:(usc,poundal)).
poundal(:(usc,poundal)).
dry_bbl(:(usc,dry_barrel)).
dry_barrel(:(usc,dry_barrel)).
hogshead(:(usc,hogshead)).
twip(:(usc,twip)).
bbl(:(usc,barrel)).
barrel(:(usc,barrel)).
min(:(usc,minim)).
minim(:(usc,minim)).
'fl dr'(:(usc,fluid_dram)).
fluid_dram(:(usc,fluid_dram)).
inHg(:(usc,inch_of_mercury)).
inch_of_mercury(:(usc,inch_of_mercury)).
tsp(:(usc,teaspoon)).
teaspoon(:(usc,teaspoon)).
'lb t'(:(usc,troy_pound)).
troy_pound(:(usc,troy_pound)).
psi(:(usc,psi)).
'oz t'(:(usc,troy_once)).
troy_once(:(usc,troy_once)).
kn(:(usc,knot)).
knot(:(usc,knot)).
cwt(:(usc,short_hundredweight)).
short_hundredweight(:(usc,short_hundredweight)).
dry_pt(:(usc,dry_pint)).
dry_pint(:(usc,dry_pint)).
ft(:(usc,foot)).
foot(:(usc,foot)).
acre(:(usc,acre)).
in(:(usc,inch)).
inch(:(usc,inch)).
t(:(usc,ton)).
ton(:(usc,ton)).
p(:(usc,point)).
point(:(usc,point)).
qt(:(usc,quart)).
quart(:(usc,quart)).
pot(:(usc,pottle)).
pottle(:(usc,pottle)).
section(:(usc,section)).
li(:(usc,link)).
link(:(usc,link)).
'P'(:(usc,pica)).
pica(:(usc,pica)).
oil_bbl(:(usc,oil_barrel)).
oil_barrel(:(usc,oil_barrel)).
nmi(:(usc,nautical_mile)).
nautical_mile(:(usc,nautical_mile)).
le(:(usc,league)).
league(:(usc,league)).
fur(:(usc,furlong)).
furlong(:(usc,furlong)).
hp(:(usc,mechanical_horsepower)).
mechanical_horsepower(:(usc,mechanical_horsepower)).
jig(:(usc,shot)).
shot(:(usc,shot)).
dwt(:(usc,pennyweight)).
pennyweight(:(usc,pennyweight)).
lbf(:(usc,pound_force)).
pound_force(:(usc,pound_force)).
dr(:(usc,dram)).
dram(:(usc,dram)).
deg_F(:(usc,degree_Fahrenheit)).
